/**
 ******************************************************************************
 *
 * @file       AltitudeHoldSettings.java
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Template for an uavobject in java
 *             This is a autogenerated file!! Do not modify and expect a result.
 *             Settings for the @ref AltitudeHold module
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package org.openpilot.uavtalk.uavobjects;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

import org.openpilot.uavtalk.UAVObjectManager;
import org.openpilot.uavtalk.UAVObject;
import org.openpilot.uavtalk.UAVDataObject;
import org.openpilot.uavtalk.UAVObjectField;

/**
Settings for the @ref AltitudeHold module

generated from altitudeholdsettings.xml
 **/
public class AltitudeHoldSettings extends UAVDataObject {

	public AltitudeHoldSettings() {
		super(OBJID, ISSINGLEINST, ISSETTINGS, NAME);
		
		List<UAVObjectField> fields = new ArrayList<UAVObjectField>();
		

		List<String> ThrustRateElemNames = new ArrayList<String>();
		ThrustRateElemNames.add("0");
		fields.add( new UAVObjectField("ThrustRate", "m/s", UAVObjectField.FieldType.FLOAT32, ThrustRateElemNames, null) );

		List<String> ThrustLimitsElemNames = new ArrayList<String>();
		ThrustLimitsElemNames.add("Min");
		ThrustLimitsElemNames.add("Neutral");
		ThrustLimitsElemNames.add("Max");
		fields.add( new UAVObjectField("ThrustLimits", "", UAVObjectField.FieldType.FLOAT32, ThrustLimitsElemNames, null) );

		List<String> VerticalPosPElemNames = new ArrayList<String>();
		VerticalPosPElemNames.add("0");
		fields.add( new UAVObjectField("VerticalPosP", "(m/s)/m", UAVObjectField.FieldType.FLOAT32, VerticalPosPElemNames, null) );

		List<String> VerticalVelPIDElemNames = new ArrayList<String>();
		VerticalVelPIDElemNames.add("Kp");
		VerticalVelPIDElemNames.add("Ki");
		VerticalVelPIDElemNames.add("Kd");
		VerticalVelPIDElemNames.add("Beta");
		fields.add( new UAVObjectField("VerticalVelPID", "(m/s^2)/(m/s)", UAVObjectField.FieldType.FLOAT32, VerticalVelPIDElemNames, null) );

		List<String> CutThrustWhenZeroElemNames = new ArrayList<String>();
		CutThrustWhenZeroElemNames.add("0");
		List<String> CutThrustWhenZeroEnumOptions = new ArrayList<String>();
		CutThrustWhenZeroEnumOptions.add("False");
		CutThrustWhenZeroEnumOptions.add("True");
		fields.add( new UAVObjectField("CutThrustWhenZero", "bool", UAVObjectField.FieldType.ENUM, CutThrustWhenZeroElemNames, CutThrustWhenZeroEnumOptions) );

		List<String> ThrustExpElemNames = new ArrayList<String>();
		ThrustExpElemNames.add("0");
		fields.add( new UAVObjectField("ThrustExp", "", UAVObjectField.FieldType.UINT8, ThrustExpElemNames, null) );


		// Compute the number of bytes for this object
		int numBytes = 0;
		ListIterator<UAVObjectField> li = fields.listIterator();
		while(li.hasNext()) {
			numBytes += li.next().getNumBytes();
		}
		NUMBYTES = numBytes;

		// Initialize object
		initializeFields(fields, ByteBuffer.allocate(NUMBYTES), NUMBYTES);
		// Set the default field values
		setDefaultFieldValues();
		// Set the object description
		setDescription(DESCRIPTION);
	}

	/**
	 * Create a Metadata object filled with default values for this object
	 * @return Metadata object with default values
	 */
	public Metadata getDefaultMetadata() {
		UAVObject.Metadata metadata = new UAVObject.Metadata();
    	metadata.flags =
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_ACCESS_SHIFT |
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_GCS_ACCESS_SHIFT |
		    1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		    1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_MANUAL) << UAVOBJ_LOGGING_UPDATE_MODE_SHIFT;
    	metadata.flightTelemetryUpdatePeriod = 0;
    	metadata.gcsTelemetryUpdatePeriod = 0;
    	metadata.loggingUpdatePeriod = 0;
 
		return metadata;
	}

	/**
	 * Initialize object fields with the default values.
	 * If a default value is not specified the object fields
	 * will be initialized to zero.
	 */
	public void setDefaultFieldValues()
	{
		getField("ThrustRate").setValue(5);
		getField("ThrustLimits").setValue(0.2,0);
		getField("ThrustLimits").setValue(0.5,1);
		getField("ThrustLimits").setValue(0.9,2);
		getField("VerticalPosP").setValue(0.7);
		getField("VerticalVelPID").setValue(0.3,0);
		getField("VerticalVelPID").setValue(0.4,1);
		getField("VerticalVelPID").setValue(0.0001,2);
		getField("VerticalVelPID").setValue(0.9,3);
		getField("CutThrustWhenZero").setValue("True");
		getField("ThrustExp").setValue(128);

	}

	/**
	 * Create a clone of this object, a new instance ID must be specified.
	 * Do not use this function directly to create new instances, the
	 * UAVObjectManager should be used instead.
	 */
	public UAVDataObject clone(long instID) {
		// TODO: Need to get specific instance to clone
		try {
			AltitudeHoldSettings obj = new AltitudeHoldSettings();
			obj.initialize(instID, this.getMetaObject());
			return obj;
		} catch  (Exception e) {
			return null;
		}
	}

	/**
	 * Returns a new instance of this UAVDataObject with default field
	 * values. This is intended to be used by 'reset to default' functionality.
	 * 
	 * @return new instance of this class with default values.
	 */
	@Override
	public UAVDataObject getDefaultInstance(){
		return new AltitudeHoldSettings();
	}

	/**
	 * Static function to retrieve an instance of the object.
	 */
	public AltitudeHoldSettings GetInstance(UAVObjectManager objMngr, long instID)
	{
	    return (AltitudeHoldSettings)(objMngr.getObject(AltitudeHoldSettings.OBJID, instID));
	}

	// Constants
	protected static final long OBJID = 0x6E3464C4l;
	protected static final String NAME = "AltitudeHoldSettings";
	protected static String DESCRIPTION = "Settings for the @ref AltitudeHold module";
	protected static final boolean ISSINGLEINST = 1 > 0;
	protected static final boolean ISSETTINGS = 1 > 0;
	protected static int NUMBYTES = 0;


}
