/**
 ******************************************************************************
 *
 * @file       CameraControlActivity.java
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Template for an uavobject in java
 *             This is a autogenerated file!! Do not modify and expect a result.
 *             Contains position and timestamp of each camera operation
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package org.openpilot.uavtalk.uavobjects;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

import org.openpilot.uavtalk.UAVObjectManager;
import org.openpilot.uavtalk.UAVObject;
import org.openpilot.uavtalk.UAVDataObject;
import org.openpilot.uavtalk.UAVObjectField;

/**
Contains position and timestamp of each camera operation

generated from cameracontrolactivity.xml
 **/
public class CameraControlActivity extends UAVDataObject {

	public CameraControlActivity() {
		super(OBJID, ISSINGLEINST, ISSETTINGS, NAME);
		
		List<UAVObjectField> fields = new ArrayList<UAVObjectField>();
		

		List<String> LatitudeElemNames = new ArrayList<String>();
		LatitudeElemNames.add("0");
		fields.add( new UAVObjectField("Latitude", "degrees x 10^-7", UAVObjectField.FieldType.INT32, LatitudeElemNames, null) );

		List<String> LongitudeElemNames = new ArrayList<String>();
		LongitudeElemNames.add("0");
		fields.add( new UAVObjectField("Longitude", "degrees x 10^-7", UAVObjectField.FieldType.INT32, LongitudeElemNames, null) );

		List<String> AltitudeElemNames = new ArrayList<String>();
		AltitudeElemNames.add("0");
		fields.add( new UAVObjectField("Altitude", "m", UAVObjectField.FieldType.FLOAT32, AltitudeElemNames, null) );

		List<String> RollElemNames = new ArrayList<String>();
		RollElemNames.add("0");
		fields.add( new UAVObjectField("Roll", "degrees", UAVObjectField.FieldType.FLOAT32, RollElemNames, null) );

		List<String> PitchElemNames = new ArrayList<String>();
		PitchElemNames.add("0");
		fields.add( new UAVObjectField("Pitch", "degrees", UAVObjectField.FieldType.FLOAT32, PitchElemNames, null) );

		List<String> YawElemNames = new ArrayList<String>();
		YawElemNames.add("0");
		fields.add( new UAVObjectField("Yaw", "degrees", UAVObjectField.FieldType.FLOAT32, YawElemNames, null) );

		List<String> SystemTSElemNames = new ArrayList<String>();
		SystemTSElemNames.add("0");
		fields.add( new UAVObjectField("SystemTS", "ms", UAVObjectField.FieldType.UINT32, SystemTSElemNames, null) );

		List<String> ImageIdElemNames = new ArrayList<String>();
		ImageIdElemNames.add("0");
		fields.add( new UAVObjectField("ImageId", "", UAVObjectField.FieldType.UINT16, ImageIdElemNames, null) );

		List<String> TriggerYearElemNames = new ArrayList<String>();
		TriggerYearElemNames.add("0");
		fields.add( new UAVObjectField("TriggerYear", "", UAVObjectField.FieldType.INT16, TriggerYearElemNames, null) );

		List<String> TriggerMillisecondElemNames = new ArrayList<String>();
		TriggerMillisecondElemNames.add("0");
		fields.add( new UAVObjectField("TriggerMillisecond", "ms", UAVObjectField.FieldType.INT16, TriggerMillisecondElemNames, null) );

		List<String> TriggerMonthElemNames = new ArrayList<String>();
		TriggerMonthElemNames.add("0");
		fields.add( new UAVObjectField("TriggerMonth", "", UAVObjectField.FieldType.INT8, TriggerMonthElemNames, null) );

		List<String> TriggerDayElemNames = new ArrayList<String>();
		TriggerDayElemNames.add("0");
		fields.add( new UAVObjectField("TriggerDay", "", UAVObjectField.FieldType.INT8, TriggerDayElemNames, null) );

		List<String> TriggerHourElemNames = new ArrayList<String>();
		TriggerHourElemNames.add("0");
		fields.add( new UAVObjectField("TriggerHour", "", UAVObjectField.FieldType.INT8, TriggerHourElemNames, null) );

		List<String> TriggerMinuteElemNames = new ArrayList<String>();
		TriggerMinuteElemNames.add("0");
		fields.add( new UAVObjectField("TriggerMinute", "", UAVObjectField.FieldType.INT8, TriggerMinuteElemNames, null) );

		List<String> TriggerSecondElemNames = new ArrayList<String>();
		TriggerSecondElemNames.add("0");
		fields.add( new UAVObjectField("TriggerSecond", "", UAVObjectField.FieldType.INT8, TriggerSecondElemNames, null) );

		List<String> ActivityElemNames = new ArrayList<String>();
		ActivityElemNames.add("0");
		List<String> ActivityEnumOptions = new ArrayList<String>();
		ActivityEnumOptions.add("Idle");
		ActivityEnumOptions.add("TriggerPicture");
		ActivityEnumOptions.add("StartVideo");
		ActivityEnumOptions.add("StopVideo");
		fields.add( new UAVObjectField("Activity", "", UAVObjectField.FieldType.ENUM, ActivityElemNames, ActivityEnumOptions) );

		List<String> ReasonElemNames = new ArrayList<String>();
		ReasonElemNames.add("0");
		List<String> ReasonEnumOptions = new ArrayList<String>();
		ReasonEnumOptions.add("Manual");
		ReasonEnumOptions.add("AutoDistance");
		ReasonEnumOptions.add("AutoTime");
		fields.add( new UAVObjectField("Reason", "", UAVObjectField.FieldType.ENUM, ReasonElemNames, ReasonEnumOptions) );


		// Compute the number of bytes for this object
		int numBytes = 0;
		ListIterator<UAVObjectField> li = fields.listIterator();
		while(li.hasNext()) {
			numBytes += li.next().getNumBytes();
		}
		NUMBYTES = numBytes;

		// Initialize object
		initializeFields(fields, ByteBuffer.allocate(NUMBYTES), NUMBYTES);
		// Set the default field values
		setDefaultFieldValues();
		// Set the object description
		setDescription(DESCRIPTION);
	}

	/**
	 * Create a Metadata object filled with default values for this object
	 * @return Metadata object with default values
	 */
	public Metadata getDefaultMetadata() {
		UAVObject.Metadata metadata = new UAVObject.Metadata();
    	metadata.flags =
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_ACCESS_SHIFT |
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_GCS_ACCESS_SHIFT |
		    0 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		    0 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_PERIODIC) << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_MANUAL) << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_MANUAL) << UAVOBJ_LOGGING_UPDATE_MODE_SHIFT;
    	metadata.flightTelemetryUpdatePeriod = 1000;
    	metadata.gcsTelemetryUpdatePeriod = 0;
    	metadata.loggingUpdatePeriod = 0;
 
		return metadata;
	}

	/**
	 * Initialize object fields with the default values.
	 * If a default value is not specified the object fields
	 * will be initialized to zero.
	 */
	public void setDefaultFieldValues()
	{

	}

	/**
	 * Create a clone of this object, a new instance ID must be specified.
	 * Do not use this function directly to create new instances, the
	 * UAVObjectManager should be used instead.
	 */
	public UAVDataObject clone(long instID) {
		// TODO: Need to get specific instance to clone
		try {
			CameraControlActivity obj = new CameraControlActivity();
			obj.initialize(instID, this.getMetaObject());
			return obj;
		} catch  (Exception e) {
			return null;
		}
	}

	/**
	 * Returns a new instance of this UAVDataObject with default field
	 * values. This is intended to be used by 'reset to default' functionality.
	 * 
	 * @return new instance of this class with default values.
	 */
	@Override
	public UAVDataObject getDefaultInstance(){
		return new CameraControlActivity();
	}

	/**
	 * Static function to retrieve an instance of the object.
	 */
	public CameraControlActivity GetInstance(UAVObjectManager objMngr, long instID)
	{
	    return (CameraControlActivity)(objMngr.getObject(CameraControlActivity.OBJID, instID));
	}

	// Constants
	protected static final long OBJID = 0x9B7A7310l;
	protected static final String NAME = "CameraControlActivity";
	protected static String DESCRIPTION = "Contains position and timestamp of each camera operation";
	protected static final boolean ISSINGLEINST = 1 > 0;
	protected static final boolean ISSETTINGS = 0 > 0;
	protected static int NUMBYTES = 0;


}
