/**
 ******************************************************************************
 *
 * @file       RevoSettings.java
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Template for an uavobject in java
 *             This is a autogenerated file!! Do not modify and expect a result.
 *             Settings for the revo to control the algorithm and what is updated
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package org.openpilot.uavtalk.uavobjects;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

import org.openpilot.uavtalk.UAVObjectManager;
import org.openpilot.uavtalk.UAVObject;
import org.openpilot.uavtalk.UAVDataObject;
import org.openpilot.uavtalk.UAVObjectField;

/**
Settings for the revo to control the algorithm and what is updated

generated from revosettings.xml
 **/
public class RevoSettings extends UAVDataObject {

	public RevoSettings() {
		super(OBJID, ISSINGLEINST, ISSETTINGS, NAME);
		
		List<UAVObjectField> fields = new ArrayList<UAVObjectField>();
		

		List<String> BaroGPSOffsetCorrectionAlphaElemNames = new ArrayList<String>();
		BaroGPSOffsetCorrectionAlphaElemNames.add("0");
		fields.add( new UAVObjectField("BaroGPSOffsetCorrectionAlpha", "", UAVObjectField.FieldType.FLOAT32, BaroGPSOffsetCorrectionAlphaElemNames, null) );

		List<String> MagnetometerMaxDeviationElemNames = new ArrayList<String>();
		MagnetometerMaxDeviationElemNames.add("Warning");
		MagnetometerMaxDeviationElemNames.add("Error");
		fields.add( new UAVObjectField("MagnetometerMaxDeviation", "%", UAVObjectField.FieldType.FLOAT32, MagnetometerMaxDeviationElemNames, null) );

		List<String> BaroTempCorrectionPolynomialElemNames = new ArrayList<String>();
		BaroTempCorrectionPolynomialElemNames.add("a");
		BaroTempCorrectionPolynomialElemNames.add("b");
		BaroTempCorrectionPolynomialElemNames.add("c");
		BaroTempCorrectionPolynomialElemNames.add("d");
		fields.add( new UAVObjectField("BaroTempCorrectionPolynomial", "", UAVObjectField.FieldType.FLOAT32, BaroTempCorrectionPolynomialElemNames, null) );

		List<String> BaroTempCorrectionExtentElemNames = new ArrayList<String>();
		BaroTempCorrectionExtentElemNames.add("min");
		BaroTempCorrectionExtentElemNames.add("max");
		fields.add( new UAVObjectField("BaroTempCorrectionExtent", "", UAVObjectField.FieldType.FLOAT32, BaroTempCorrectionExtentElemNames, null) );

		List<String> VelocityPostProcessingLowPassAlphaElemNames = new ArrayList<String>();
		VelocityPostProcessingLowPassAlphaElemNames.add("0");
		fields.add( new UAVObjectField("VelocityPostProcessingLowPassAlpha", "", UAVObjectField.FieldType.FLOAT32, VelocityPostProcessingLowPassAlphaElemNames, null) );

		List<String> FusionAlgorithmElemNames = new ArrayList<String>();
		FusionAlgorithmElemNames.add("0");
		List<String> FusionAlgorithmEnumOptions = new ArrayList<String>();
		FusionAlgorithmEnumOptions.add("None");
		FusionAlgorithmEnumOptions.add("Basic (Complementary)");
		FusionAlgorithmEnumOptions.add("Complementary+Mag");
		FusionAlgorithmEnumOptions.add("Complementary+Mag+GPSOutdoor");
		FusionAlgorithmEnumOptions.add("INS13Indoor");
		FusionAlgorithmEnumOptions.add("GPS Navigation (INS13)");
		FusionAlgorithmEnumOptions.add("GPS Navigation (INS13+CF)");
		FusionAlgorithmEnumOptions.add("Testing (INS Indoor+CF)");
		fields.add( new UAVObjectField("FusionAlgorithm", "", UAVObjectField.FieldType.ENUM, FusionAlgorithmElemNames, FusionAlgorithmEnumOptions) );


		// Compute the number of bytes for this object
		int numBytes = 0;
		ListIterator<UAVObjectField> li = fields.listIterator();
		while(li.hasNext()) {
			numBytes += li.next().getNumBytes();
		}
		NUMBYTES = numBytes;

		// Initialize object
		initializeFields(fields, ByteBuffer.allocate(NUMBYTES), NUMBYTES);
		// Set the default field values
		setDefaultFieldValues();
		// Set the object description
		setDescription(DESCRIPTION);
	}

	/**
	 * Create a Metadata object filled with default values for this object
	 * @return Metadata object with default values
	 */
	public Metadata getDefaultMetadata() {
		UAVObject.Metadata metadata = new UAVObject.Metadata();
    	metadata.flags =
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_ACCESS_SHIFT |
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_GCS_ACCESS_SHIFT |
		    1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		    1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_MANUAL) << UAVOBJ_LOGGING_UPDATE_MODE_SHIFT;
    	metadata.flightTelemetryUpdatePeriod = 0;
    	metadata.gcsTelemetryUpdatePeriod = 0;
    	metadata.loggingUpdatePeriod = 0;
 
		return metadata;
	}

	/**
	 * Initialize object fields with the default values.
	 * If a default value is not specified the object fields
	 * will be initialized to zero.
	 */
	public void setDefaultFieldValues()
	{
		getField("BaroGPSOffsetCorrectionAlpha").setValue(0.999334);
		getField("MagnetometerMaxDeviation").setValue(0.05,0);
		getField("MagnetometerMaxDeviation").setValue(0.15,1);
		getField("BaroTempCorrectionPolynomial").setValue(0,0);
		getField("BaroTempCorrectionPolynomial").setValue(0,1);
		getField("BaroTempCorrectionPolynomial").setValue(0,2);
		getField("BaroTempCorrectionPolynomial").setValue(0,3);
		getField("BaroTempCorrectionExtent").setValue(0,0);
		getField("BaroTempCorrectionExtent").setValue(0,1);
		getField("VelocityPostProcessingLowPassAlpha").setValue(0.999);
		getField("FusionAlgorithm").setValue("Basic (Complementary)");

	}

	/**
	 * Create a clone of this object, a new instance ID must be specified.
	 * Do not use this function directly to create new instances, the
	 * UAVObjectManager should be used instead.
	 */
	public UAVDataObject clone(long instID) {
		// TODO: Need to get specific instance to clone
		try {
			RevoSettings obj = new RevoSettings();
			obj.initialize(instID, this.getMetaObject());
			return obj;
		} catch  (Exception e) {
			return null;
		}
	}

	/**
	 * Returns a new instance of this UAVDataObject with default field
	 * values. This is intended to be used by 'reset to default' functionality.
	 * 
	 * @return new instance of this class with default values.
	 */
	@Override
	public UAVDataObject getDefaultInstance(){
		return new RevoSettings();
	}

	/**
	 * Static function to retrieve an instance of the object.
	 */
	public RevoSettings GetInstance(UAVObjectManager objMngr, long instID)
	{
	    return (RevoSettings)(objMngr.getObject(RevoSettings.OBJID, instID));
	}

	// Constants
	protected static final long OBJID = 0xAC90E79El;
	protected static final String NAME = "RevoSettings";
	protected static String DESCRIPTION = "Settings for the revo to control the algorithm and what is updated";
	protected static final boolean ISSINGLEINST = 1 > 0;
	protected static final boolean ISSETTINGS = 1 > 0;
	protected static int NUMBYTES = 0;


}
