/**
 ******************************************************************************
 *
 * @file       SystemIdentSettings.java
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Template for an uavobject in java
 *             This is a autogenerated file!! Do not modify and expect a result.
 *             The input to and results of the PID tuning.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package org.openpilot.uavtalk.uavobjects;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;

import org.openpilot.uavtalk.UAVObjectManager;
import org.openpilot.uavtalk.UAVObject;
import org.openpilot.uavtalk.UAVDataObject;
import org.openpilot.uavtalk.UAVObjectField;

/**
The input to and results of the PID tuning.

generated from systemidentsettings.xml
 **/
public class SystemIdentSettings extends UAVDataObject {

	public SystemIdentSettings() {
		super(OBJID, ISSINGLEINST, ISSETTINGS, NAME);
		
		List<UAVObjectField> fields = new ArrayList<UAVObjectField>();
		

		List<String> TauElemNames = new ArrayList<String>();
		TauElemNames.add("0");
		fields.add( new UAVObjectField("Tau", "ln(sec)", UAVObjectField.FieldType.FLOAT32, TauElemNames, null) );

		List<String> BetaElemNames = new ArrayList<String>();
		BetaElemNames.add("Roll");
		BetaElemNames.add("Pitch");
		BetaElemNames.add("Yaw");
		fields.add( new UAVObjectField("Beta", "", UAVObjectField.FieldType.FLOAT32, BetaElemNames, null) );

		List<String> YawToRollPitchPIDRatioMinElemNames = new ArrayList<String>();
		YawToRollPitchPIDRatioMinElemNames.add("0");
		fields.add( new UAVObjectField("YawToRollPitchPIDRatioMin", "", UAVObjectField.FieldType.FLOAT32, YawToRollPitchPIDRatioMinElemNames, null) );

		List<String> YawToRollPitchPIDRatioMaxElemNames = new ArrayList<String>();
		YawToRollPitchPIDRatioMaxElemNames.add("0");
		fields.add( new UAVObjectField("YawToRollPitchPIDRatioMax", "", UAVObjectField.FieldType.FLOAT32, YawToRollPitchPIDRatioMaxElemNames, null) );

		List<String> DerivativeFactorElemNames = new ArrayList<String>();
		DerivativeFactorElemNames.add("0");
		fields.add( new UAVObjectField("DerivativeFactor", "", UAVObjectField.FieldType.FLOAT32, DerivativeFactorElemNames, null) );

		List<String> OuterLoopKpSoftClampElemNames = new ArrayList<String>();
		OuterLoopKpSoftClampElemNames.add("0");
		fields.add( new UAVObjectField("OuterLoopKpSoftClamp", "", UAVObjectField.FieldType.FLOAT32, OuterLoopKpSoftClampElemNames, null) );

		List<String> SmoothQuickValueElemNames = new ArrayList<String>();
		SmoothQuickValueElemNames.add("0");
		fields.add( new UAVObjectField("SmoothQuickValue", "", UAVObjectField.FieldType.FLOAT32, SmoothQuickValueElemNames, null) );

		List<String> GyroReadTimeAverageElemNames = new ArrayList<String>();
		GyroReadTimeAverageElemNames.add("0");
		fields.add( new UAVObjectField("GyroReadTimeAverage", "s", UAVObjectField.FieldType.FLOAT32, GyroReadTimeAverageElemNames, null) );

		List<String> DampMinElemNames = new ArrayList<String>();
		DampMinElemNames.add("0");
		fields.add( new UAVObjectField("DampMin", "", UAVObjectField.FieldType.UINT8, DampMinElemNames, null) );

		List<String> DampRateElemNames = new ArrayList<String>();
		DampRateElemNames.add("0");
		fields.add( new UAVObjectField("DampRate", "", UAVObjectField.FieldType.UINT8, DampRateElemNames, null) );

		List<String> DampMaxElemNames = new ArrayList<String>();
		DampMaxElemNames.add("0");
		fields.add( new UAVObjectField("DampMax", "", UAVObjectField.FieldType.UINT8, DampMaxElemNames, null) );

		List<String> NoiseMinElemNames = new ArrayList<String>();
		NoiseMinElemNames.add("0");
		fields.add( new UAVObjectField("NoiseMin", "", UAVObjectField.FieldType.UINT8, NoiseMinElemNames, null) );

		List<String> NoiseRateElemNames = new ArrayList<String>();
		NoiseRateElemNames.add("0");
		fields.add( new UAVObjectField("NoiseRate", "", UAVObjectField.FieldType.UINT8, NoiseRateElemNames, null) );

		List<String> NoiseMaxElemNames = new ArrayList<String>();
		NoiseMaxElemNames.add("0");
		fields.add( new UAVObjectField("NoiseMax", "", UAVObjectField.FieldType.UINT8, NoiseMaxElemNames, null) );

		List<String> CalculateYawElemNames = new ArrayList<String>();
		CalculateYawElemNames.add("0");
		List<String> CalculateYawEnumOptions = new ArrayList<String>();
		CalculateYawEnumOptions.add("False");
		CalculateYawEnumOptions.add("TrueLimitToRatio");
		CalculateYawEnumOptions.add("TrueIgnoreLimit");
		fields.add( new UAVObjectField("CalculateYaw", "", UAVObjectField.FieldType.ENUM, CalculateYawElemNames, CalculateYawEnumOptions) );

		List<String> DestinationPidBankElemNames = new ArrayList<String>();
		DestinationPidBankElemNames.add("0");
		fields.add( new UAVObjectField("DestinationPidBank", "bank#", UAVObjectField.FieldType.UINT8, DestinationPidBankElemNames, null) );

		List<String> TuningDurationElemNames = new ArrayList<String>();
		TuningDurationElemNames.add("0");
		fields.add( new UAVObjectField("TuningDuration", "s", UAVObjectField.FieldType.UINT8, TuningDurationElemNames, null) );

		List<String> ThrustControlElemNames = new ArrayList<String>();
		ThrustControlElemNames.add("0");
		List<String> ThrustControlEnumOptions = new ArrayList<String>();
		ThrustControlEnumOptions.add("Manual");
		ThrustControlEnumOptions.add("AltitudeVario");
		fields.add( new UAVObjectField("ThrustControl", "", UAVObjectField.FieldType.ENUM, ThrustControlElemNames, ThrustControlEnumOptions) );

		List<String> SmoothQuickSourceElemNames = new ArrayList<String>();
		SmoothQuickSourceElemNames.add("0");
		fields.add( new UAVObjectField("SmoothQuickSource", "", UAVObjectField.FieldType.UINT8, SmoothQuickSourceElemNames, null) );

		List<String> DisableSanityChecksElemNames = new ArrayList<String>();
		DisableSanityChecksElemNames.add("0");
		List<String> DisableSanityChecksEnumOptions = new ArrayList<String>();
		DisableSanityChecksEnumOptions.add("False");
		DisableSanityChecksEnumOptions.add("True");
		fields.add( new UAVObjectField("DisableSanityChecks", "bool", UAVObjectField.FieldType.ENUM, DisableSanityChecksElemNames, DisableSanityChecksEnumOptions) );

		List<String> CompleteElemNames = new ArrayList<String>();
		CompleteElemNames.add("0");
		List<String> CompleteEnumOptions = new ArrayList<String>();
		CompleteEnumOptions.add("False");
		CompleteEnumOptions.add("True");
		fields.add( new UAVObjectField("Complete", "bool", UAVObjectField.FieldType.ENUM, CompleteElemNames, CompleteEnumOptions) );


		// Compute the number of bytes for this object
		int numBytes = 0;
		ListIterator<UAVObjectField> li = fields.listIterator();
		while(li.hasNext()) {
			numBytes += li.next().getNumBytes();
		}
		NUMBYTES = numBytes;

		// Initialize object
		initializeFields(fields, ByteBuffer.allocate(NUMBYTES), NUMBYTES);
		// Set the default field values
		setDefaultFieldValues();
		// Set the object description
		setDescription(DESCRIPTION);
	}

	/**
	 * Create a Metadata object filled with default values for this object
	 * @return Metadata object with default values
	 */
	public Metadata getDefaultMetadata() {
		UAVObject.Metadata metadata = new UAVObject.Metadata();
    	metadata.flags =
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_ACCESS_SHIFT |
		    UAVObject.Metadata.AccessModeNum(UAVObject.AccessMode.ACCESS_READWRITE) << UAVOBJ_GCS_ACCESS_SHIFT |
		    1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
		    1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_ONCHANGE) << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT |
		    UAVObject.Metadata.UpdateModeNum(UAVObject.UpdateMode.UPDATEMODE_MANUAL) << UAVOBJ_LOGGING_UPDATE_MODE_SHIFT;
    	metadata.flightTelemetryUpdatePeriod = 0;
    	metadata.gcsTelemetryUpdatePeriod = 0;
    	metadata.loggingUpdatePeriod = 0;
 
		return metadata;
	}

	/**
	 * Initialize object fields with the default values.
	 * If a default value is not specified the object fields
	 * will be initialized to zero.
	 */
	public void setDefaultFieldValues()
	{
		getField("Tau").setValue(-4);
		getField("Beta").setValue(10,0);
		getField("Beta").setValue(10,1);
		getField("Beta").setValue(7,2);
		getField("YawToRollPitchPIDRatioMin").setValue(1);
		getField("YawToRollPitchPIDRatioMax").setValue(2.5);
		getField("DerivativeFactor").setValue(1);
		getField("OuterLoopKpSoftClamp").setValue(6.5);
		getField("SmoothQuickValue").setValue(0);
		getField("GyroReadTimeAverage").setValue(0.001);
		getField("DampMin").setValue(90);
		getField("DampRate").setValue(110);
		getField("DampMax").setValue(150);
		getField("NoiseMin").setValue(6);
		getField("NoiseRate").setValue(10);
		getField("NoiseMax").setValue(16);
		getField("CalculateYaw").setValue("TrueLimitToRatio");
		getField("DestinationPidBank").setValue(3);
		getField("TuningDuration").setValue(60);
		getField("ThrustControl").setValue("Manual");
		getField("SmoothQuickSource").setValue(25);
		getField("DisableSanityChecks").setValue("False");
		getField("Complete").setValue("False");

	}

	/**
	 * Create a clone of this object, a new instance ID must be specified.
	 * Do not use this function directly to create new instances, the
	 * UAVObjectManager should be used instead.
	 */
	public UAVDataObject clone(long instID) {
		// TODO: Need to get specific instance to clone
		try {
			SystemIdentSettings obj = new SystemIdentSettings();
			obj.initialize(instID, this.getMetaObject());
			return obj;
		} catch  (Exception e) {
			return null;
		}
	}

	/**
	 * Returns a new instance of this UAVDataObject with default field
	 * values. This is intended to be used by 'reset to default' functionality.
	 * 
	 * @return new instance of this class with default values.
	 */
	@Override
	public UAVDataObject getDefaultInstance(){
		return new SystemIdentSettings();
	}

	/**
	 * Static function to retrieve an instance of the object.
	 */
	public SystemIdentSettings GetInstance(UAVObjectManager objMngr, long instID)
	{
	    return (SystemIdentSettings)(objMngr.getObject(SystemIdentSettings.OBJID, instID));
	}

	// Constants
	protected static final long OBJID = 0xE660D37Al;
	protected static final String NAME = "SystemIdentSettings";
	protected static String DESCRIPTION = "The input to and results of the PID tuning.";
	protected static final boolean ISSINGLEINST = 1 > 0;
	protected static final boolean ISSETTINGS = 1 > 0;
	protected static int NUMBYTES = 0;


}
