/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup AccelState AccelState
 * @brief The filtered acceleration data.
 *
 * Autogenerated files and functions for AccelState Object
 *
 * @{
 *
 * @file       accelstate.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the AccelState object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: accelstate.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef ACCELSTATE_H
#define ACCELSTATE_H
#include <stdbool.h>
/* Object constants */
#define ACCELSTATE_OBJID 0xAD3C0E06
#define ACCELSTATE_ISSINGLEINST 1
#define ACCELSTATE_ISSETTINGS 0
#define ACCELSTATE_ISPRIORITY 0
#define ACCELSTATE_NUMBYTES sizeof(AccelStateData)

/* Field x information */

/* Field y information */

/* Field z information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float x;
    float y;
    float z;

} __attribute__((packed)) AccelStateDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef AccelStateDataPacked __attribute__((aligned(4))) AccelStateData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    AccelStateDataPacked data;
    byte arr[ACCELSTATE_NUMBYTES];
 } AccelStateDataUnion;

#endif // ACCELSTATE_H

/**
 * @}
 * @}
 */
