/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup BaroSensor BaroSensor
 * @brief The raw data from the barometric sensor with pressure, temperature and altitude estimate.
 *
 * Autogenerated files and functions for BaroSensor Object
 *
 * @{
 *
 * @file       barosensor.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the BaroSensor object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: barosensor.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef BAROSENSOR_H
#define BAROSENSOR_H
#include <stdbool.h>
/* Object constants */
#define BAROSENSOR_OBJID 0x48120EA6
#define BAROSENSOR_ISSINGLEINST 1
#define BAROSENSOR_ISSETTINGS 0
#define BAROSENSOR_ISPRIORITY 0
#define BAROSENSOR_NUMBYTES sizeof(BaroSensorData)

/* Field Altitude information */

/* Field Temperature information */

/* Field Pressure information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float Altitude;
    float Temperature;
    float Pressure;

} __attribute__((packed)) BaroSensorDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef BaroSensorDataPacked __attribute__((aligned(4))) BaroSensorData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    BaroSensorDataPacked data;
    byte arr[BAROSENSOR_NUMBYTES];
 } BaroSensorDataUnion;

#endif // BAROSENSOR_H

/**
 * @}
 * @}
 */
