/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup DebugLogControl DebugLogControl
 * @brief Log Control Object - Used to issue commands to the on board logging system
 *
 * Autogenerated files and functions for DebugLogControl Object
 *
 * @{
 *
 * @file       debuglogcontrol.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the DebugLogControl object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: debuglogcontrol.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef DEBUGLOGCONTROL_H
#define DEBUGLOGCONTROL_H
#include <stdbool.h>
/* Object constants */
#define DEBUGLOGCONTROL_OBJID 0xC39642FC
#define DEBUGLOGCONTROL_ISSINGLEINST 1
#define DEBUGLOGCONTROL_ISSETTINGS 0
#define DEBUGLOGCONTROL_ISPRIORITY 0
#define DEBUGLOGCONTROL_NUMBYTES sizeof(DebugLogControlData)

/* Field Flight information */

/* Field Entry information */

/* Field Operation information */

// Enumeration options for field Operation
typedef enum __attribute__ ((__packed__)) {
    DEBUGLOGCONTROL_OPERATION_NONE=0,
    DEBUGLOGCONTROL_OPERATION_RETRIEVE=1,
    DEBUGLOGCONTROL_OPERATION_FORMATFLASH=2
} DebugLogControlOperationOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    uint16_t Flight;
    uint16_t Entry;
    DebugLogControlOperationOptions Operation;

} __attribute__((packed)) DebugLogControlDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef DebugLogControlDataPacked __attribute__((aligned(4))) DebugLogControlData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    DebugLogControlDataPacked data;
    byte arr[DEBUGLOGCONTROL_NUMBYTES];
 } DebugLogControlDataUnion;

#endif // DEBUGLOGCONTROL_H

/**
 * @}
 * @}
 */
