/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup FaultSettings FaultSettings
 * @brief Allows testers to simulate various fault scenarios.
 *
 * Autogenerated files and functions for FaultSettings Object
 *
 * @{
 *
 * @file       faultsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the FaultSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: faultsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef FAULTSETTINGS_H
#define FAULTSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define FAULTSETTINGS_OBJID 0x2778BA3C
#define FAULTSETTINGS_ISSINGLEINST 1
#define FAULTSETTINGS_ISSETTINGS 1
#define FAULTSETTINGS_ISPRIORITY 0
#define FAULTSETTINGS_NUMBYTES sizeof(FaultSettingsData)

/* Field ActivateFault information */

// Enumeration options for field ActivateFault
typedef enum __attribute__ ((__packed__)) {
    FAULTSETTINGS_ACTIVATEFAULT_NOFAULT=0,
    FAULTSETTINGS_ACTIVATEFAULT_MODULEINITASSERT=1,
    FAULTSETTINGS_ACTIVATEFAULT_INITOUTOFMEMORY=2,
    FAULTSETTINGS_ACTIVATEFAULT_INITBUSERROR=3,
    FAULTSETTINGS_ACTIVATEFAULT_RUNAWAYTASK=4,
    FAULTSETTINGS_ACTIVATEFAULT_TASKOUTOFMEMORY=5
} FaultSettingsActivateFaultOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    FaultSettingsActivateFaultOptions ActivateFault;

} __attribute__((packed)) FaultSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef FaultSettingsDataPacked __attribute__((aligned(4))) FaultSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    FaultSettingsDataPacked data;
    byte arr[FAULTSETTINGS_NUMBYTES];
 } FaultSettingsDataUnion;

#endif // FAULTSETTINGS_H

/**
 * @}
 * @}
 */
