/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup FlightPlanControl FlightPlanControl
 * @brief Control the flight plan script
 *
 * Autogenerated files and functions for FlightPlanControl Object
 *
 * @{
 *
 * @file       flightplancontrol.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the FlightPlanControl object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: flightplancontrol.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef FLIGHTPLANCONTROL_H
#define FLIGHTPLANCONTROL_H
#include <stdbool.h>
/* Object constants */
#define FLIGHTPLANCONTROL_OBJID 0x53E3F180
#define FLIGHTPLANCONTROL_ISSINGLEINST 1
#define FLIGHTPLANCONTROL_ISSETTINGS 0
#define FLIGHTPLANCONTROL_ISPRIORITY 0
#define FLIGHTPLANCONTROL_NUMBYTES sizeof(FlightPlanControlData)

/* Field Command information */

// Enumeration options for field Command
typedef enum __attribute__ ((__packed__)) {
    FLIGHTPLANCONTROL_COMMAND_START=0,
    FLIGHTPLANCONTROL_COMMAND_STOP=1,
    FLIGHTPLANCONTROL_COMMAND_KILL=2
} FlightPlanControlCommandOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    FlightPlanControlCommandOptions Command;

} __attribute__((packed)) FlightPlanControlDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef FlightPlanControlDataPacked __attribute__((aligned(4))) FlightPlanControlData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    FlightPlanControlDataPacked data;
    byte arr[FLIGHTPLANCONTROL_NUMBYTES];
 } FlightPlanControlDataUnion;

#endif // FLIGHTPLANCONTROL_H

/**
 * @}
 * @}
 */
