/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup I2CStats I2CStats
 * @brief Tracks statistics on the I2C bus.
 *
 * Autogenerated files and functions for I2CStats Object
 *
 * @{
 *
 * @file       i2cstats.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the I2CStats object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: i2cstats.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef I2CSTATS_H
#define I2CSTATS_H
#include <stdbool.h>
/* Object constants */
#define I2CSTATS_OBJID 0xB714823E
#define I2CSTATS_ISSINGLEINST 1
#define I2CSTATS_ISSETTINGS 0
#define I2CSTATS_ISPRIORITY 0
#define I2CSTATS_NUMBYTES sizeof(I2CStatsData)

/* Field evirq_log information */

// Number of elements for field evirq_log
#define I2CSTATS_EVIRQ_LOG_NUMELEM 5

/* Field erirq_log information */

// Number of elements for field erirq_log
#define I2CSTATS_ERIRQ_LOG_NUMELEM 5

/* Field event_errors information */

/* Field fsm_errors information */

/* Field irq_errors information */

/* Field nacks information */

/* Field timeouts information */

/* Field last_error_type information */

// Enumeration options for field last_error_type
typedef enum __attribute__ ((__packed__)) {
    I2CSTATS_LAST_ERROR_TYPE_EVENT=0,
    I2CSTATS_LAST_ERROR_TYPE_FSM=1,
    I2CSTATS_LAST_ERROR_TYPE_INTERRUPT=2
} I2CStatslast_error_typeOptions;

/* Field event_log information */

// Enumeration options for field event_log
typedef enum __attribute__ ((__packed__)) {
    I2CSTATS_EVENT_LOG_I2C_EVENT_BUS_ERROR=0,
    I2CSTATS_EVENT_LOG_I2C_EVENT_START=1,
    I2CSTATS_EVENT_LOG_I2C_EVENT_STARTED_MORE_TXN_READ=2,
    I2CSTATS_EVENT_LOG_I2C_EVENT_STARTED_MORE_TXN_WRITE=3,
    I2CSTATS_EVENT_LOG_I2C_EVENT_STARTED_LAST_TXN_READ=4,
    I2CSTATS_EVENT_LOG_I2C_EVENT_STARTED_LAST_TXN_WRITE=5,
    I2CSTATS_EVENT_LOG_I2C_EVENT_ADDR_SENT_LEN_EQ_0=6,
    I2CSTATS_EVENT_LOG_I2C_EVENT_ADDR_SENT_LEN_EQ_1=7,
    I2CSTATS_EVENT_LOG_I2C_EVENT_ADDR_SENT_LEN_EQ_2=8,
    I2CSTATS_EVENT_LOG_I2C_EVENT_ADDR_SENT_LEN_GT_2=9,
    I2CSTATS_EVENT_LOG_I2C_EVENT_TRANSFER_DONE_LEN_EQ_0=10,
    I2CSTATS_EVENT_LOG_I2C_EVENT_TRANSFER_DONE_LEN_EQ_1=11,
    I2CSTATS_EVENT_LOG_I2C_EVENT_TRANSFER_DONE_LEN_EQ_2=12,
    I2CSTATS_EVENT_LOG_I2C_EVENT_TRANSFER_DONE_LEN_GT_2=13,
    I2CSTATS_EVENT_LOG_I2C_EVENT_NACK=14,
    I2CSTATS_EVENT_LOG_I2C_EVENT_STOPPED=15,
    I2CSTATS_EVENT_LOG_I2C_EVENT_AUTO=16
} I2CStatsevent_logOptions;

// Number of elements for field event_log
#define I2CSTATS_EVENT_LOG_NUMELEM 5

/* Field state_log information */

// Enumeration options for field state_log
typedef enum __attribute__ ((__packed__)) {
    I2CSTATS_STATE_LOG_I2C_STATE_FSM_FAULT=0,
    I2CSTATS_STATE_LOG_I2C_STATE_BUS_ERROR=1,
    I2CSTATS_STATE_LOG_I2C_STATE_STOPPED=2,
    I2CSTATS_STATE_LOG_I2C_STATE_STOPPING=3,
    I2CSTATS_STATE_LOG_I2C_STATE_STARTING=4,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_ADDR=5,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_PRE_ONE=6,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_PRE_FIRST=7,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_PRE_MIDDLE=8,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_LAST=9,
    I2CSTATS_STATE_LOG_I2C_STATE_R_MORE_TXN_POST_LAST=10,
    I2CSTATS_STATE_LOG_R_LAST_TXN_ADDR=11,
    I2CSTATS_STATE_LOG_I2C_STATE_R_LAST_TXN_PRE_ONE=12,
    I2CSTATS_STATE_LOG_I2C_STATE_R_LAST_TXN_PRE_FIRST=13,
    I2CSTATS_STATE_LOG_I2C_STATE_R_LAST_TXN_PRE_MIDDLE=14,
    I2CSTATS_STATE_LOG_I2C_STATE_R_LAST_TXN_PRE_LAST=15,
    I2CSTATS_STATE_LOG_I2C_STATE_R_LAST_TXN_POST_LAST=16,
    I2CSTATS_STATE_LOG_I2C_STATE_W_MORE_TXN_ADDR=17,
    I2CSTATS_STATE_LOG_I2C_STATE_W_MORE_TXN_MIDDLE=18,
    I2CSTATS_STATE_LOG_I2C_STATE_W_MORE_TXN_LAST=19,
    I2CSTATS_STATE_LOG_I2C_STATE_W_LAST_TXN_ADDR=20,
    I2CSTATS_STATE_LOG_I2C_STATE_W_LAST_TXN_MIDDLE=21,
    I2CSTATS_STATE_LOG_I2C_STATE_W_LAST_TXN_LAST=22,
    I2CSTATS_STATE_LOG_I2C_STATE_NACK=23
} I2CStatsstate_logOptions;

// Number of elements for field state_log
#define I2CSTATS_STATE_LOG_NUMELEM 5




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    uint32_t evirq_log[5];
    uint32_t erirq_log[5];
    uint8_t event_errors;
    uint8_t fsm_errors;
    uint8_t irq_errors;
    uint8_t nacks;
    uint8_t timeouts;
    I2CStatslast_error_typeOptions last_error_type;
    I2CStatsevent_logOptions event_log[5];
    I2CStatsstate_logOptions state_log[5];

} __attribute__((packed)) I2CStatsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef I2CStatsDataPacked __attribute__((aligned(4))) I2CStatsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    I2CStatsDataPacked data;
    byte arr[I2CSTATS_NUMBYTES];
 } I2CStatsDataUnion;

#endif // I2CSTATS_H

/**
 * @}
 * @}
 */
