/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup MagState MagState
 * @brief The filtered magnet vector.
 *
 * Autogenerated files and functions for MagState Object
 *
 * @{
 *
 * @file       magstate.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the MagState object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: magstate.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MAGSTATE_H
#define MAGSTATE_H
#include <stdbool.h>
/* Object constants */
#define MAGSTATE_OBJID 0x9FFEAA0C
#define MAGSTATE_ISSINGLEINST 1
#define MAGSTATE_ISSETTINGS 0
#define MAGSTATE_ISPRIORITY 0
#define MAGSTATE_NUMBYTES sizeof(MagStateData)

/* Field x information */

/* Field y information */

/* Field z information */

/* Field Source information */

// Enumeration options for field Source
typedef enum __attribute__ ((__packed__)) {
    MAGSTATE_SOURCE_INVALID=0,
    MAGSTATE_SOURCE_ONBOARD=1,
    MAGSTATE_SOURCE_AUX=2
} MagStateSourceOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float x;
    float y;
    float z;
    MagStateSourceOptions Source;

} __attribute__((packed)) MagStateDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef MagStateDataPacked __attribute__((aligned(4))) MagStateData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    MagStateDataPacked data;
    byte arr[MAGSTATE_NUMBYTES];
 } MagStateDataUnion;

#endif // MAGSTATE_H

/**
 * @}
 * @}
 */
