/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup OveroSyncSettings OveroSyncSettings
 * @brief Settings to control the behavior of the overo sync module
 *
 * Autogenerated files and functions for OveroSyncSettings Object
 *
 * @{
 *
 * @file       overosyncsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the OveroSyncSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: overosyncsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef OVEROSYNCSETTINGS_H
#define OVEROSYNCSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define OVEROSYNCSETTINGS_OBJID 0xA1ABC278
#define OVEROSYNCSETTINGS_ISSINGLEINST 1
#define OVEROSYNCSETTINGS_ISSETTINGS 1
#define OVEROSYNCSETTINGS_ISPRIORITY 0
#define OVEROSYNCSETTINGS_NUMBYTES sizeof(OveroSyncSettingsData)

/* Field LogOn information */

// Enumeration options for field LogOn
typedef enum __attribute__ ((__packed__)) {
    OVEROSYNCSETTINGS_LOGON_NEVER=0,
    OVEROSYNCSETTINGS_LOGON_ALWAYS=1,
    OVEROSYNCSETTINGS_LOGON_ARMED=2
} OveroSyncSettingsLogOnOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    OveroSyncSettingsLogOnOptions LogOn;

} __attribute__((packed)) OveroSyncSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef OveroSyncSettingsDataPacked __attribute__((aligned(4))) OveroSyncSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    OveroSyncSettingsDataPacked data;
    byte arr[OVEROSYNCSETTINGS_NUMBYTES];
 } OveroSyncSettingsDataUnion;

#endif // OVEROSYNCSETTINGS_H

/**
 * @}
 * @}
 */
