/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup DebugLogSettings DebugLogSettings
 * @brief Configure On Board Logging Facilities
 *
 * Autogenerated files and functions for DebugLogSettings Object
 *
 * @{
 *
 * @file       debuglogsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the DebugLogSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: debuglogsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef DEBUGLOGSETTINGS_H
#define DEBUGLOGSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define DEBUGLOGSETTINGS_OBJID 0x5E5903CC
#define DEBUGLOGSETTINGS_ISSINGLEINST 1
#define DEBUGLOGSETTINGS_ISSETTINGS 1
#define DEBUGLOGSETTINGS_ISPRIORITY 0
#define DEBUGLOGSETTINGS_NUMBYTES sizeof(DebugLogSettingsData)

/* Field LoggingEnabled information */

// Enumeration options for field LoggingEnabled
typedef enum __attribute__ ((__packed__)) {
    DEBUGLOGSETTINGS_LOGGINGENABLED_DISABLED=0,
    DEBUGLOGSETTINGS_LOGGINGENABLED_ONLYWHENARMED=1,
    DEBUGLOGSETTINGS_LOGGINGENABLED_ALWAYS=2
} DebugLogSettingsLoggingEnabledOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    DebugLogSettingsLoggingEnabledOptions LoggingEnabled;

} __attribute__((packed)) DebugLogSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef DebugLogSettingsDataPacked __attribute__((aligned(4))) DebugLogSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    DebugLogSettingsDataPacked data;
    byte arr[DEBUGLOGSETTINGS_NUMBYTES];
 } DebugLogSettingsDataUnion;

#endif // DEBUGLOGSETTINGS_H

/**
 * @}
 * @}
 */
