/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup FlightTelemetryStats FlightTelemetryStats
 * @brief Maintains the telemetry statistics from the OpenPilot flight computer.
 *
 * Autogenerated files and functions for FlightTelemetryStats Object
 *
 * @{
 *
 * @file       flighttelemetrystats.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the FlightTelemetryStats object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: flighttelemetrystats.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef FLIGHTTELEMETRYSTATS_H
#define FLIGHTTELEMETRYSTATS_H
#include <stdbool.h>
/* Object constants */
#define FLIGHTTELEMETRYSTATS_OBJID 0x6737BB5A
#define FLIGHTTELEMETRYSTATS_ISSINGLEINST 1
#define FLIGHTTELEMETRYSTATS_ISSETTINGS 0
#define FLIGHTTELEMETRYSTATS_ISPRIORITY 1
#define FLIGHTTELEMETRYSTATS_NUMBYTES sizeof(FlightTelemetryStatsData)

/* Field TxDataRate information */

/* Field TxBytes information */

/* Field TxFailures information */

/* Field TxRetries information */

/* Field RxDataRate information */

/* Field RxBytes information */

/* Field RxFailures information */

/* Field RxSyncErrors information */

/* Field RxCrcErrors information */

/* Field Status information */

// Enumeration options for field Status
typedef enum __attribute__ ((__packed__)) {
    FLIGHTTELEMETRYSTATS_STATUS_DISCONNECTED=0,
    FLIGHTTELEMETRYSTATS_STATUS_HANDSHAKEREQ=1,
    FLIGHTTELEMETRYSTATS_STATUS_HANDSHAKEACK=2,
    FLIGHTTELEMETRYSTATS_STATUS_CONNECTED=3
} FlightTelemetryStatsStatusOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float TxDataRate;
    uint32_t TxBytes;
    uint32_t TxFailures;
    uint32_t TxRetries;
    float RxDataRate;
    uint32_t RxBytes;
    uint32_t RxFailures;
    uint32_t RxSyncErrors;
    uint32_t RxCrcErrors;
    FlightTelemetryStatsStatusOptions Status;

} __attribute__((packed)) FlightTelemetryStatsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef FlightTelemetryStatsDataPacked __attribute__((aligned(4))) FlightTelemetryStatsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    FlightTelemetryStatsDataPacked data;
    byte arr[FLIGHTTELEMETRYSTATS_NUMBYTES];
 } FlightTelemetryStatsDataUnion;

#endif // FLIGHTTELEMETRYSTATS_H

/**
 * @}
 * @}
 */
