/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup GPSPositionSensor GPSPositionSensor
 * @brief Raw GPS data from @ref GPSModule.
 *
 * Autogenerated files and functions for GPSPositionSensor Object
 *
 * @{
 *
 * @file       gpspositionsensor.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the GPSPositionSensor object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: gpspositionsensor.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef GPSPOSITIONSENSOR_H
#define GPSPOSITIONSENSOR_H
#include <stdbool.h>
/* Object constants */
#define GPSPOSITIONSENSOR_OBJID 0x9DF1F67A
#define GPSPOSITIONSENSOR_ISSINGLEINST 1
#define GPSPOSITIONSENSOR_ISSETTINGS 0
#define GPSPOSITIONSENSOR_ISPRIORITY 0
#define GPSPOSITIONSENSOR_NUMBYTES sizeof(GPSPositionSensorData)

/* Field Latitude information */

/* Field Longitude information */

/* Field Altitude information */

/* Field GeoidSeparation information */

/* Field Heading information */

/* Field Groundspeed information */

/* Field PDOP information */

/* Field HDOP information */

/* Field VDOP information */

/* Field Status information */

// Enumeration options for field Status
typedef enum __attribute__ ((__packed__)) {
    GPSPOSITIONSENSOR_STATUS_NOGPS=0,
    GPSPOSITIONSENSOR_STATUS_NOFIX=1,
    GPSPOSITIONSENSOR_STATUS_FIX2D=2,
    GPSPOSITIONSENSOR_STATUS_FIX3D=3
} GPSPositionSensorStatusOptions;

/* Field Satellites information */

/* Field SensorType information */

// Enumeration options for field SensorType
typedef enum __attribute__ ((__packed__)) {
    GPSPOSITIONSENSOR_SENSORTYPE_UNKNOWN=0,
    GPSPOSITIONSENSOR_SENSORTYPE_NMEA=1,
    GPSPOSITIONSENSOR_SENSORTYPE_UBX=2,
    GPSPOSITIONSENSOR_SENSORTYPE_UBX7=3,
    GPSPOSITIONSENSOR_SENSORTYPE_UBX8=4,
    GPSPOSITIONSENSOR_SENSORTYPE_DJI=5
} GPSPositionSensorSensorTypeOptions;

/* Field AutoConfigStatus information */

// Enumeration options for field AutoConfigStatus
typedef enum __attribute__ ((__packed__)) {
    GPSPOSITIONSENSOR_AUTOCONFIGSTATUS_DISABLED=0,
    GPSPOSITIONSENSOR_AUTOCONFIGSTATUS_RUNNING=1,
    GPSPOSITIONSENSOR_AUTOCONFIGSTATUS_DONE=2,
    GPSPOSITIONSENSOR_AUTOCONFIGSTATUS_ERROR=3
} GPSPositionSensorAutoConfigStatusOptions;

/* Field BaudRate information */

// Enumeration options for field BaudRate
typedef enum __attribute__ ((__packed__)) {
    GPSPOSITIONSENSOR_BAUDRATE_2400=0,
    GPSPOSITIONSENSOR_BAUDRATE_4800=1,
    GPSPOSITIONSENSOR_BAUDRATE_9600=2,
    GPSPOSITIONSENSOR_BAUDRATE_19200=3,
    GPSPOSITIONSENSOR_BAUDRATE_38400=4,
    GPSPOSITIONSENSOR_BAUDRATE_57600=5,
    GPSPOSITIONSENSOR_BAUDRATE_115200=6,
    GPSPOSITIONSENSOR_BAUDRATE_230400=7,
    GPSPOSITIONSENSOR_BAUDRATE_UNKNOWN=8
} GPSPositionSensorBaudRateOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    int32_t Latitude;
    int32_t Longitude;
    float Altitude;
    float GeoidSeparation;
    float Heading;
    float Groundspeed;
    float PDOP;
    float HDOP;
    float VDOP;
    GPSPositionSensorStatusOptions Status;
    int8_t Satellites;
    GPSPositionSensorSensorTypeOptions SensorType;
    GPSPositionSensorAutoConfigStatusOptions AutoConfigStatus;
    GPSPositionSensorBaudRateOptions BaudRate;

} __attribute__((packed)) GPSPositionSensorDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef GPSPositionSensorDataPacked __attribute__((aligned(4))) GPSPositionSensorData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    GPSPositionSensorDataPacked data;
    byte arr[GPSPOSITIONSENSOR_NUMBYTES];
 } GPSPositionSensorDataUnion;

#endif // GPSPOSITIONSENSOR_H

/**
 * @}
 * @}
 */
