/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup GPSSettings GPSSettings
 * @brief GPS Module specific settings
 *
 * Autogenerated files and functions for GPSSettings Object
 *
 * @{
 *
 * @file       gpssettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the GPSSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: gpssettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef GPSSETTINGS_H
#define GPSSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define GPSSETTINGS_OBJID 0xF300A164
#define GPSSETTINGS_ISSINGLEINST 1
#define GPSSETTINGS_ISSETTINGS 1
#define GPSSETTINGS_ISPRIORITY 0
#define GPSSETTINGS_NUMBYTES sizeof(GPSSettingsData)

/* Field MaxPDOP information */

/* Field DataProtocol information */

// Enumeration options for field DataProtocol
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_DATAPROTOCOL_NMEA=0,
    GPSSETTINGS_DATAPROTOCOL_UBX=1,
    GPSSETTINGS_DATAPROTOCOL_DJI=2
} GPSSettingsDataProtocolOptions;

/* Field MinSatellites information */

/* Field UbxAutoConfig information */

// Enumeration options for field UbxAutoConfig
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXAUTOCONFIG_DISABLED=0,
    GPSSETTINGS_UBXAUTOCONFIG_AUTOBAUD=1,
    GPSSETTINGS_UBXAUTOCONFIG_AUTOBAUDANDCONFIGURE=2,
    GPSSETTINGS_UBXAUTOCONFIG_AUTOBAUDCONFIGUREANDSTORE=3,
    GPSSETTINGS_UBXAUTOCONFIG_AUTOBAUDCONFIGURESTOREANDDISABLE=4
} GPSSettingsUbxAutoConfigOptions;

/* Field UbxRate information */

/* Field UbxDynamicModel information */

// Enumeration options for field UbxDynamicModel
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXDYNAMICMODEL_PORTABLE=0,
    GPSSETTINGS_UBXDYNAMICMODEL_STATIONARY=1,
    GPSSETTINGS_UBXDYNAMICMODEL_PEDESTRIAN=2,
    GPSSETTINGS_UBXDYNAMICMODEL_AUTOMOTIVE=3,
    GPSSETTINGS_UBXDYNAMICMODEL_SEA=4,
    GPSSETTINGS_UBXDYNAMICMODEL_AIRBORNE1G=5,
    GPSSETTINGS_UBXDYNAMICMODEL_AIRBORNE2G=6,
    GPSSETTINGS_UBXDYNAMICMODEL_AIRBORNE4G=7
} GPSSettingsUbxDynamicModelOptions;

/* Field UbxSBASMode information */

// Enumeration options for field UbxSBASMode
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXSBASMODE_DISABLED=0,
    GPSSETTINGS_UBXSBASMODE_RANGING=1,
    GPSSETTINGS_UBXSBASMODE_CORRECTION=2,
    GPSSETTINGS_UBXSBASMODE_INTEGRITY=3,
    GPSSETTINGS_UBXSBASMODE_RANGINGCORRECTION=4,
    GPSSETTINGS_UBXSBASMODE_RANGINGINTEGRITY=5,
    GPSSETTINGS_UBXSBASMODE_RANGINGCORRECTIONINTEGRITY=6,
    GPSSETTINGS_UBXSBASMODE_CORRECTIONINTEGRITY=7
} GPSSettingsUbxSBASModeOptions;

/* Field UbxSBASChannelsUsed information */

/* Field UbxSBASSats information */

// Enumeration options for field UbxSBASSats
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXSBASSATS_AUTOSCAN=0,
    GPSSETTINGS_UBXSBASSATS_WAAS=1,
    GPSSETTINGS_UBXSBASSATS_EGNOS=2,
    GPSSETTINGS_UBXSBASSATS_MSAS=3,
    GPSSETTINGS_UBXSBASSATS_GAGAN=4,
    GPSSETTINGS_UBXSBASSATS_SDCM=5
} GPSSettingsUbxSBASSatsOptions;

/* Field UbxGNSSMode information */

// Enumeration options for field UbxGNSSMode
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXGNSSMODE_DEFAULT=0,
    GPSSETTINGS_UBXGNSSMODE_GPS=1,
    GPSSETTINGS_UBXGNSSMODE_GLONASS=2,
    GPSSETTINGS_UBXGNSSMODE_GPSGLONASS=3,
    GPSSETTINGS_UBXGNSSMODE_GPSBEIDOU=4,
    GPSSETTINGS_UBXGNSSMODE_GLONASSBEIDOU=5,
    GPSSETTINGS_UBXGNSSMODE_GPSGALILEO=6,
    GPSSETTINGS_UBXGNSSMODE_GPSGLONASSGALILEO=7
} GPSSettingsUbxGNSSModeOptions;

/* Field UbxAssistNowAutonomous information */

// Enumeration options for field UbxAssistNowAutonomous
typedef enum __attribute__ ((__packed__)) {
    GPSSETTINGS_UBXASSISTNOWAUTONOMOUS_FALSE=0,
    GPSSETTINGS_UBXASSISTNOWAUTONOMOUS_TRUE=1
} GPSSettingsUbxAssistNowAutonomousOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float MaxPDOP;
    GPSSettingsDataProtocolOptions DataProtocol;
    uint8_t MinSatellites;
    GPSSettingsUbxAutoConfigOptions UbxAutoConfig;
    int8_t UbxRate;
    GPSSettingsUbxDynamicModelOptions UbxDynamicModel;
    GPSSettingsUbxSBASModeOptions UbxSBASMode;
    uint8_t UbxSBASChannelsUsed;
    GPSSettingsUbxSBASSatsOptions UbxSBASSats;
    GPSSettingsUbxGNSSModeOptions UbxGNSSMode;
    GPSSettingsUbxAssistNowAutonomousOptions UbxAssistNowAutonomous;

} __attribute__((packed)) GPSSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef GPSSettingsDataPacked __attribute__((aligned(4))) GPSSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    GPSSettingsDataPacked data;
    byte arr[GPSSETTINGS_NUMBYTES];
 } GPSSettingsDataUnion;

#endif // GPSSETTINGS_H

/**
 * @}
 * @}
 */
