/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup MixerSettings MixerSettings
 * @brief Settings for the @ref ActuatorModule that controls the channel assignments for the mixer based on AircraftType
 *
 * Autogenerated files and functions for MixerSettings Object
 *
 * @{
 *
 * @file       mixersettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the MixerSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: mixersettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MIXERSETTINGS_H
#define MIXERSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define MIXERSETTINGS_OBJID 0x4CB44DAC
#define MIXERSETTINGS_ISSINGLEINST 1
#define MIXERSETTINGS_ISSETTINGS 1
#define MIXERSETTINGS_ISPRIORITY 0
#define MIXERSETTINGS_NUMBYTES sizeof(MixerSettingsData)

/* Field ThrottleCurve1 information */

// Array element names for field ThrottleCurve1
typedef enum {
    MIXERSETTINGS_THROTTLECURVE1_0=0,
    MIXERSETTINGS_THROTTLECURVE1_25=1,
    MIXERSETTINGS_THROTTLECURVE1_50=2,
    MIXERSETTINGS_THROTTLECURVE1_75=3,
    MIXERSETTINGS_THROTTLECURVE1_100=4
} MixerSettingsThrottleCurve1Elem;

// Number of elements for field ThrottleCurve1
#define MIXERSETTINGS_THROTTLECURVE1_NUMELEM 5

/* Field ThrottleCurve2 information */

// Array element names for field ThrottleCurve2
typedef enum {
    MIXERSETTINGS_THROTTLECURVE2_0=0,
    MIXERSETTINGS_THROTTLECURVE2_25=1,
    MIXERSETTINGS_THROTTLECURVE2_50=2,
    MIXERSETTINGS_THROTTLECURVE2_75=3,
    MIXERSETTINGS_THROTTLECURVE2_100=4
} MixerSettingsThrottleCurve2Elem;

// Number of elements for field ThrottleCurve2
#define MIXERSETTINGS_THROTTLECURVE2_NUMELEM 5

/* Field MixerValueRoll information */

/* Field MixerValuePitch information */

/* Field MixerValueYaw information */

/* Field RollDifferential information */

/* Field FirstRollServo information */

/* Field Curve2Source information */

// Enumeration options for field Curve2Source
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_CURVE2SOURCE_THROTTLE=0,
    MIXERSETTINGS_CURVE2SOURCE_ROLL=1,
    MIXERSETTINGS_CURVE2SOURCE_PITCH=2,
    MIXERSETTINGS_CURVE2SOURCE_YAW=3,
    MIXERSETTINGS_CURVE2SOURCE_COLLECTIVE=4,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY0=5,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY1=6,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY2=7,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY3=8,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY4=9,
    MIXERSETTINGS_CURVE2SOURCE_ACCESSORY5=10
} MixerSettingsCurve2SourceOptions;

/* Field Mixer1Type information */

// Enumeration options for field Mixer1Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER1TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER1TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER1TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER1TYPE_SERVO=3,
    MIXERSETTINGS_MIXER1TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER1TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER1TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER1TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER1TYPE_ACCESSORY5=13
} MixerSettingsMixer1TypeOptions;

/* Field Mixer1Vector information */

// Array element names for field Mixer1Vector
typedef enum {
    MIXERSETTINGS_MIXER1VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER1VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER1VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER1VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER1VECTOR_YAW=4
} MixerSettingsMixer1VectorElem;

// Number of elements for field Mixer1Vector
#define MIXERSETTINGS_MIXER1VECTOR_NUMELEM 5

/* Field Mixer2Type information */

// Enumeration options for field Mixer2Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER2TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER2TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER2TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER2TYPE_SERVO=3,
    MIXERSETTINGS_MIXER2TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER2TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER2TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER2TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER2TYPE_ACCESSORY5=13
} MixerSettingsMixer2TypeOptions;

/* Field Mixer2Vector information */

// Array element names for field Mixer2Vector
typedef enum {
    MIXERSETTINGS_MIXER2VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER2VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER2VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER2VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER2VECTOR_YAW=4
} MixerSettingsMixer2VectorElem;

// Number of elements for field Mixer2Vector
#define MIXERSETTINGS_MIXER2VECTOR_NUMELEM 5

/* Field Mixer3Type information */

// Enumeration options for field Mixer3Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER3TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER3TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER3TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER3TYPE_SERVO=3,
    MIXERSETTINGS_MIXER3TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER3TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER3TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER3TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER3TYPE_ACCESSORY5=13
} MixerSettingsMixer3TypeOptions;

/* Field Mixer3Vector information */

// Array element names for field Mixer3Vector
typedef enum {
    MIXERSETTINGS_MIXER3VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER3VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER3VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER3VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER3VECTOR_YAW=4
} MixerSettingsMixer3VectorElem;

// Number of elements for field Mixer3Vector
#define MIXERSETTINGS_MIXER3VECTOR_NUMELEM 5

/* Field Mixer4Type information */

// Enumeration options for field Mixer4Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER4TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER4TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER4TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER4TYPE_SERVO=3,
    MIXERSETTINGS_MIXER4TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER4TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER4TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER4TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER4TYPE_ACCESSORY5=13
} MixerSettingsMixer4TypeOptions;

/* Field Mixer4Vector information */

// Array element names for field Mixer4Vector
typedef enum {
    MIXERSETTINGS_MIXER4VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER4VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER4VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER4VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER4VECTOR_YAW=4
} MixerSettingsMixer4VectorElem;

// Number of elements for field Mixer4Vector
#define MIXERSETTINGS_MIXER4VECTOR_NUMELEM 5

/* Field Mixer5Type information */

// Enumeration options for field Mixer5Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER5TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER5TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER5TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER5TYPE_SERVO=3,
    MIXERSETTINGS_MIXER5TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER5TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER5TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER5TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER5TYPE_ACCESSORY5=13
} MixerSettingsMixer5TypeOptions;

/* Field Mixer5Vector information */

// Array element names for field Mixer5Vector
typedef enum {
    MIXERSETTINGS_MIXER5VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER5VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER5VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER5VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER5VECTOR_YAW=4
} MixerSettingsMixer5VectorElem;

// Number of elements for field Mixer5Vector
#define MIXERSETTINGS_MIXER5VECTOR_NUMELEM 5

/* Field Mixer6Type information */

// Enumeration options for field Mixer6Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER6TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER6TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER6TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER6TYPE_SERVO=3,
    MIXERSETTINGS_MIXER6TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER6TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER6TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER6TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER6TYPE_ACCESSORY5=13
} MixerSettingsMixer6TypeOptions;

/* Field Mixer6Vector information */

// Array element names for field Mixer6Vector
typedef enum {
    MIXERSETTINGS_MIXER6VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER6VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER6VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER6VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER6VECTOR_YAW=4
} MixerSettingsMixer6VectorElem;

// Number of elements for field Mixer6Vector
#define MIXERSETTINGS_MIXER6VECTOR_NUMELEM 5

/* Field Mixer7Type information */

// Enumeration options for field Mixer7Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER7TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER7TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER7TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER7TYPE_SERVO=3,
    MIXERSETTINGS_MIXER7TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER7TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER7TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER7TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER7TYPE_ACCESSORY5=13
} MixerSettingsMixer7TypeOptions;

/* Field Mixer7Vector information */

// Array element names for field Mixer7Vector
typedef enum {
    MIXERSETTINGS_MIXER7VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER7VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER7VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER7VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER7VECTOR_YAW=4
} MixerSettingsMixer7VectorElem;

// Number of elements for field Mixer7Vector
#define MIXERSETTINGS_MIXER7VECTOR_NUMELEM 5

/* Field Mixer8Type information */

// Enumeration options for field Mixer8Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER8TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER8TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER8TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER8TYPE_SERVO=3,
    MIXERSETTINGS_MIXER8TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER8TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER8TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER8TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER8TYPE_ACCESSORY5=13
} MixerSettingsMixer8TypeOptions;

/* Field Mixer8Vector information */

// Array element names for field Mixer8Vector
typedef enum {
    MIXERSETTINGS_MIXER8VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER8VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER8VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER8VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER8VECTOR_YAW=4
} MixerSettingsMixer8VectorElem;

// Number of elements for field Mixer8Vector
#define MIXERSETTINGS_MIXER8VECTOR_NUMELEM 5

/* Field Mixer9Type information */

// Enumeration options for field Mixer9Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER9TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER9TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER9TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER9TYPE_SERVO=3,
    MIXERSETTINGS_MIXER9TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER9TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER9TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER9TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER9TYPE_ACCESSORY5=13
} MixerSettingsMixer9TypeOptions;

/* Field Mixer9Vector information */

// Array element names for field Mixer9Vector
typedef enum {
    MIXERSETTINGS_MIXER9VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER9VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER9VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER9VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER9VECTOR_YAW=4
} MixerSettingsMixer9VectorElem;

// Number of elements for field Mixer9Vector
#define MIXERSETTINGS_MIXER9VECTOR_NUMELEM 5

/* Field Mixer10Type information */

// Enumeration options for field Mixer10Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER10TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER10TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER10TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER10TYPE_SERVO=3,
    MIXERSETTINGS_MIXER10TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER10TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER10TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER10TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER10TYPE_ACCESSORY5=13
} MixerSettingsMixer10TypeOptions;

/* Field Mixer10Vector information */

// Array element names for field Mixer10Vector
typedef enum {
    MIXERSETTINGS_MIXER10VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER10VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER10VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER10VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER10VECTOR_YAW=4
} MixerSettingsMixer10VectorElem;

// Number of elements for field Mixer10Vector
#define MIXERSETTINGS_MIXER10VECTOR_NUMELEM 5

/* Field Mixer11Type information */

// Enumeration options for field Mixer11Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER11TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER11TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER11TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER11TYPE_SERVO=3,
    MIXERSETTINGS_MIXER11TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER11TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER11TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER11TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER11TYPE_ACCESSORY5=13
} MixerSettingsMixer11TypeOptions;

/* Field Mixer11Vector information */

// Array element names for field Mixer11Vector
typedef enum {
    MIXERSETTINGS_MIXER11VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER11VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER11VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER11VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER11VECTOR_YAW=4
} MixerSettingsMixer11VectorElem;

// Number of elements for field Mixer11Vector
#define MIXERSETTINGS_MIXER11VECTOR_NUMELEM 5

/* Field Mixer12Type information */

// Enumeration options for field Mixer12Type
typedef enum __attribute__ ((__packed__)) {
    MIXERSETTINGS_MIXER12TYPE_DISABLED=0,
    MIXERSETTINGS_MIXER12TYPE_MOTOR=1,
    MIXERSETTINGS_MIXER12TYPE_REVERSABLEMOTOR=2,
    MIXERSETTINGS_MIXER12TYPE_SERVO=3,
    MIXERSETTINGS_MIXER12TYPE_CAMERAROLLORSERVO1=4,
    MIXERSETTINGS_MIXER12TYPE_CAMERAPITCHORSERVO2=5,
    MIXERSETTINGS_MIXER12TYPE_CAMERAYAW=6,
    MIXERSETTINGS_MIXER12TYPE_CAMERATRIGGER=7,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY0=8,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY1=9,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY2=10,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY3=11,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY4=12,
    MIXERSETTINGS_MIXER12TYPE_ACCESSORY5=13
} MixerSettingsMixer12TypeOptions;

/* Field Mixer12Vector information */

// Array element names for field Mixer12Vector
typedef enum {
    MIXERSETTINGS_MIXER12VECTOR_THROTTLECURVE1=0,
    MIXERSETTINGS_MIXER12VECTOR_THROTTLECURVE2=1,
    MIXERSETTINGS_MIXER12VECTOR_ROLL=2,
    MIXERSETTINGS_MIXER12VECTOR_PITCH=3,
    MIXERSETTINGS_MIXER12VECTOR_YAW=4
} MixerSettingsMixer12VectorElem;

// Number of elements for field Mixer12Vector
#define MIXERSETTINGS_MIXER12VECTOR_NUMELEM 5



typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer1VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer1VectorDataArray ;
#define MixerSettingsMixer1VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer1VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer2VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer2VectorDataArray ;
#define MixerSettingsMixer2VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer2VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer3VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer3VectorDataArray ;
#define MixerSettingsMixer3VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer3VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer4VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer4VectorDataArray ;
#define MixerSettingsMixer4VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer4VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer5VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer5VectorDataArray ;
#define MixerSettingsMixer5VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer5VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer6VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer6VectorDataArray ;
#define MixerSettingsMixer6VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer6VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer7VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer7VectorDataArray ;
#define MixerSettingsMixer7VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer7VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer8VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer8VectorDataArray ;
#define MixerSettingsMixer8VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer8VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer9VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer9VectorDataArray ;
#define MixerSettingsMixer9VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer9VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer10VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer10VectorDataArray ;
#define MixerSettingsMixer10VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer10VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer11VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer11VectorDataArray ;
#define MixerSettingsMixer11VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer11VectorData, var )

typedef struct __attribute__ ((__packed__)) {
    int8_t ThrottleCurve1;
    int8_t ThrottleCurve2;
    int8_t Roll;
    int8_t Pitch;
    int8_t Yaw;
}  MixerSettingsMixer12VectorData ;
typedef struct __attribute__ ((__packed__)) {
    int8_t array[5];
}  MixerSettingsMixer12VectorDataArray ;
#define MixerSettingsMixer12VectorToArray( var ) UAVObjectFieldToArray( MixerSettingsMixer12VectorData, var )


/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float ThrottleCurve1[5];
    float ThrottleCurve2[5];
    int8_t MixerValueRoll;
    int8_t MixerValuePitch;
    int8_t MixerValueYaw;
    int8_t RollDifferential;
    uint8_t FirstRollServo;
    MixerSettingsCurve2SourceOptions Curve2Source;
    MixerSettingsMixer1TypeOptions Mixer1Type;
    MixerSettingsMixer1VectorData Mixer1Vector;
    MixerSettingsMixer2TypeOptions Mixer2Type;
    MixerSettingsMixer2VectorData Mixer2Vector;
    MixerSettingsMixer3TypeOptions Mixer3Type;
    MixerSettingsMixer3VectorData Mixer3Vector;
    MixerSettingsMixer4TypeOptions Mixer4Type;
    MixerSettingsMixer4VectorData Mixer4Vector;
    MixerSettingsMixer5TypeOptions Mixer5Type;
    MixerSettingsMixer5VectorData Mixer5Vector;
    MixerSettingsMixer6TypeOptions Mixer6Type;
    MixerSettingsMixer6VectorData Mixer6Vector;
    MixerSettingsMixer7TypeOptions Mixer7Type;
    MixerSettingsMixer7VectorData Mixer7Vector;
    MixerSettingsMixer8TypeOptions Mixer8Type;
    MixerSettingsMixer8VectorData Mixer8Vector;
    MixerSettingsMixer9TypeOptions Mixer9Type;
    MixerSettingsMixer9VectorData Mixer9Vector;
    MixerSettingsMixer10TypeOptions Mixer10Type;
    MixerSettingsMixer10VectorData Mixer10Vector;
    MixerSettingsMixer11TypeOptions Mixer11Type;
    MixerSettingsMixer11VectorData Mixer11Vector;
    MixerSettingsMixer12TypeOptions Mixer12Type;
    MixerSettingsMixer12VectorData Mixer12Vector;

} __attribute__((packed)) MixerSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef MixerSettingsDataPacked __attribute__((aligned(4))) MixerSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    MixerSettingsDataPacked data;
    byte arr[MIXERSETTINGS_NUMBYTES];
 } MixerSettingsDataUnion;

#endif // MIXERSETTINGS_H

/**
 * @}
 * @}
 */
