/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup MPUGyroAccelSettings MPUGyroAccelSettings
 * @brief Settings for the @ref MPU6000 and MPU9000 sensor series. Used in CC3D, Revolution and RevoBone. Reboot the board for this to takes effect
 *
 * Autogenerated files and functions for MPUGyroAccelSettings Object
 *
 * @{
 *
 * @file       mpugyroaccelsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the MPUGyroAccelSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: mpugyroaccelsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MPUGYROACCELSETTINGS_H
#define MPUGYROACCELSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define MPUGYROACCELSETTINGS_OBJID 0x7E2826C8
#define MPUGYROACCELSETTINGS_ISSINGLEINST 1
#define MPUGYROACCELSETTINGS_ISSETTINGS 1
#define MPUGYROACCELSETTINGS_ISPRIORITY 0
#define MPUGYROACCELSETTINGS_NUMBYTES sizeof(MPUGyroAccelSettingsData)

/* Field GyroScale information */

// Enumeration options for field GyroScale
typedef enum __attribute__ ((__packed__)) {
    MPUGYROACCELSETTINGS_GYROSCALE_SCALE_250=0,
    MPUGYROACCELSETTINGS_GYROSCALE_SCALE_500=1,
    MPUGYROACCELSETTINGS_GYROSCALE_SCALE_1000=2,
    MPUGYROACCELSETTINGS_GYROSCALE_SCALE_2000=3
} MPUGyroAccelSettingsGyroScaleOptions;

/* Field AccelScale information */

// Enumeration options for field AccelScale
typedef enum __attribute__ ((__packed__)) {
    MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_2G=0,
    MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_4G=1,
    MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_8G=2,
    MPUGYROACCELSETTINGS_ACCELSCALE_SCALE_16G=3
} MPUGyroAccelSettingsAccelScaleOptions;

/* Field FilterSetting information */

// Enumeration options for field FilterSetting
typedef enum __attribute__ ((__packed__)) {
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_256_HZ=0,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_188_HZ=1,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_98_HZ=2,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_42_HZ=3,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_20_HZ=4,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_10_HZ=5,
    MPUGYROACCELSETTINGS_FILTERSETTING_LOWPASS_5_HZ=6
} MPUGyroAccelSettingsFilterSettingOptions;




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    MPUGyroAccelSettingsGyroScaleOptions GyroScale;
    MPUGyroAccelSettingsAccelScaleOptions AccelScale;
    MPUGyroAccelSettingsFilterSettingOptions FilterSetting;

} __attribute__((packed)) MPUGyroAccelSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef MPUGyroAccelSettingsDataPacked __attribute__((aligned(4))) MPUGyroAccelSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    MPUGyroAccelSettingsDataPacked data;
    byte arr[MPUGYROACCELSETTINGS_NUMBYTES];
 } MPUGyroAccelSettingsDataUnion;

#endif // MPUGYROACCELSETTINGS_H

/**
 * @}
 * @}
 */
