/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup OPLinkReceiver OPLinkReceiver
 * @brief A receiver channel group carried over the OPLink radio.
 *
 * Autogenerated files and functions for OPLinkReceiver Object
 *
 * @{
 *
 * @file       oplinkreceiver.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the OPLinkReceiver object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: oplinkreceiver.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef OPLINKRECEIVER_H
#define OPLINKRECEIVER_H
#include <stdbool.h>
/* Object constants */
#define OPLINKRECEIVER_OBJID 0xD29CFD2
#define OPLINKRECEIVER_ISSINGLEINST 1
#define OPLINKRECEIVER_ISSETTINGS 0
#define OPLINKRECEIVER_ISPRIORITY 0
#define OPLINKRECEIVER_NUMBYTES sizeof(OPLinkReceiverData)

/* Field Channel information */

// Number of elements for field Channel
#define OPLINKRECEIVER_CHANNEL_NUMELEM 16




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    int16_t Channel[16];

} __attribute__((packed)) OPLinkReceiverDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef OPLinkReceiverDataPacked __attribute__((aligned(4))) OPLinkReceiverData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    OPLinkReceiverDataPacked data;
    byte arr[OPLINKRECEIVER_NUMBYTES];
 } OPLinkReceiverDataUnion;

#endif // OPLINKRECEIVER_H

/**
 * @}
 * @}
 */
