/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup PathPlan PathPlan
 * @brief Flight plan informations
 *
 * Autogenerated files and functions for PathPlan Object
 *
 * @{
 *
 * @file       pathplan.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the PathPlan object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: pathplan.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef PATHPLAN_H
#define PATHPLAN_H
#include <stdbool.h>
/* Object constants */
#define PATHPLAN_OBJID 0x82F5D500
#define PATHPLAN_ISSINGLEINST 1
#define PATHPLAN_ISSETTINGS 0
#define PATHPLAN_ISPRIORITY 0
#define PATHPLAN_NUMBYTES sizeof(PathPlanData)

/* Field WaypointCount information */

/* Field PathActionCount information */

/* Field Crc information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    uint16_t WaypointCount;
    uint16_t PathActionCount;
    uint8_t Crc;

} __attribute__((packed)) PathPlanDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef PathPlanDataPacked __attribute__((aligned(4))) PathPlanData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    PathPlanDataPacked data;
    byte arr[PATHPLAN_NUMBYTES];
 } PathPlanDataUnion;

#endif // PATHPLAN_H

/**
 * @}
 * @}
 */
