/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup PIDStatus PIDStatus
 * @brief Status of a PID loop for debugging
 *
 * Autogenerated files and functions for PIDStatus Object
 *
 * @{
 *
 * @file       pidstatus.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the PIDStatus object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: pidstatus.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef PIDSTATUS_H
#define PIDSTATUS_H
#include <stdbool.h>
/* Object constants */
#define PIDSTATUS_OBJID 0x75CF70A6
#define PIDSTATUS_ISSINGLEINST 1
#define PIDSTATUS_ISSETTINGS 0
#define PIDSTATUS_ISPRIORITY 0
#define PIDSTATUS_NUMBYTES sizeof(PIDStatusData)

/* Field setpoint information */

/* Field actual information */

/* Field error information */

/* Field ulow information */

/* Field uhigh information */

/* Field command information */

/* Field P information */

/* Field I information */

/* Field D information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float setpoint;
    float actual;
    float error;
    float ulow;
    float uhigh;
    float command;
    float P;
    float I;
    float D;

} __attribute__((packed)) PIDStatusDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef PIDStatusDataPacked __attribute__((aligned(4))) PIDStatusData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    PIDStatusDataPacked data;
    byte arr[PIDSTATUS_NUMBYTES];
 } PIDStatusDataUnion;

#endif // PIDSTATUS_H

/**
 * @}
 * @}
 */
