/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup SystemIdentSettings SystemIdentSettings
 * @brief The input to and results of the PID tuning.
 *
 * Autogenerated files and functions for SystemIdentSettings Object
 *
 * @{
 *
 * @file       systemidentsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the SystemIdentSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: systemidentsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef SYSTEMIDENTSETTINGS_H
#define SYSTEMIDENTSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define SYSTEMIDENTSETTINGS_OBJID 0xCECA91B6
#define SYSTEMIDENTSETTINGS_ISSINGLEINST 1
#define SYSTEMIDENTSETTINGS_ISSETTINGS 1
#define SYSTEMIDENTSETTINGS_ISPRIORITY 0
#define SYSTEMIDENTSETTINGS_NUMBYTES sizeof(SystemIdentSettingsData)

/* Field Tau information */

/* Field Beta information */

// Array element names for field Beta
typedef enum {
    SYSTEMIDENTSETTINGS_BETA_ROLL=0,
    SYSTEMIDENTSETTINGS_BETA_PITCH=1,
    SYSTEMIDENTSETTINGS_BETA_YAW=2
} SystemIdentSettingsBetaElem;

// Number of elements for field Beta
#define SYSTEMIDENTSETTINGS_BETA_NUMELEM 3

/* Field YawToRollPitchPIDRatioMin information */

/* Field YawToRollPitchPIDRatioMax information */

/* Field DerivativeFactor information */

/* Field OuterLoopKpSoftClamp information */

/* Field SmoothQuickValue information */

/* Field GyroReadTimeAverage information */

/* Field DampMin information */

/* Field DampRate information */

/* Field DampMax information */

/* Field NoiseMin information */

/* Field NoiseRate information */

/* Field NoiseMax information */

/* Field CalculateYaw information */

// Enumeration options for field CalculateYaw
typedef enum __attribute__ ((__packed__)) {
    SYSTEMIDENTSETTINGS_CALCULATEYAW_FALSE=0,
    SYSTEMIDENTSETTINGS_CALCULATEYAW_TRUELIMITTORATIO=1,
    SYSTEMIDENTSETTINGS_CALCULATEYAW_TRUEIGNORELIMIT=2
} SystemIdentSettingsCalculateYawOptions;

/* Field DestinationPidBank information */

/* Field TuningDuration information */

/* Field SmoothQuickSource information */

/* Field DisableSanityChecks information */

// Enumeration options for field DisableSanityChecks
typedef enum __attribute__ ((__packed__)) {
    SYSTEMIDENTSETTINGS_DISABLESANITYCHECKS_FALSE=0,
    SYSTEMIDENTSETTINGS_DISABLESANITYCHECKS_TRUE=1
} SystemIdentSettingsDisableSanityChecksOptions;

/* Field Complete information */

// Enumeration options for field Complete
typedef enum __attribute__ ((__packed__)) {
    SYSTEMIDENTSETTINGS_COMPLETE_FALSE=0,
    SYSTEMIDENTSETTINGS_COMPLETE_TRUE=1
} SystemIdentSettingsCompleteOptions;



typedef struct __attribute__ ((__packed__)) {
    float Roll;
    float Pitch;
    float Yaw;
}  SystemIdentSettingsBetaData ;
typedef struct __attribute__ ((__packed__)) {
    float array[3];
}  SystemIdentSettingsBetaDataArray ;
#define SystemIdentSettingsBetaToArray( var ) UAVObjectFieldToArray( SystemIdentSettingsBetaData, var )


/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float Tau;
    SystemIdentSettingsBetaData Beta;
    float YawToRollPitchPIDRatioMin;
    float YawToRollPitchPIDRatioMax;
    float DerivativeFactor;
    float OuterLoopKpSoftClamp;
    float SmoothQuickValue;
    float GyroReadTimeAverage;
    uint8_t DampMin;
    uint8_t DampRate;
    uint8_t DampMax;
    uint8_t NoiseMin;
    uint8_t NoiseRate;
    uint8_t NoiseMax;
    SystemIdentSettingsCalculateYawOptions CalculateYaw;
    uint8_t DestinationPidBank;
    uint8_t TuningDuration;
    uint8_t SmoothQuickSource;
    SystemIdentSettingsDisableSanityChecksOptions DisableSanityChecks;
    SystemIdentSettingsCompleteOptions Complete;

} __attribute__((packed)) SystemIdentSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef SystemIdentSettingsDataPacked __attribute__((aligned(4))) SystemIdentSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    SystemIdentSettingsDataPacked data;
    byte arr[SYSTEMIDENTSETTINGS_NUMBYTES];
 } SystemIdentSettingsDataUnion;

#endif // SYSTEMIDENTSETTINGS_H

/**
 * @}
 * @}
 */
