/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup SystemAlarms SystemAlarms
 * @brief Alarms from OpenPilot to indicate failure conditions or warnings.  Set by various modules.  Some modules may have a module defined Status and Substatus fields that details its condition.
 *
 * Autogenerated files and functions for SystemAlarms Object
 *
 * @{
 *
 * @file       systemalarms.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the SystemAlarms object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: systemalarms.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef SYSTEMALARMS_H
#define SYSTEMALARMS_H
#include <stdbool.h>
/* Object constants */
#define SYSTEMALARMS_OBJID 0x85C20346
#define SYSTEMALARMS_ISSINGLEINST 1
#define SYSTEMALARMS_ISSETTINGS 0
#define SYSTEMALARMS_ISPRIORITY 1
#define SYSTEMALARMS_NUMBYTES sizeof(SystemAlarmsData)

/* Field Alarm information */

// Enumeration options for field Alarm
typedef enum __attribute__ ((__packed__)) {
    SYSTEMALARMS_ALARM_UNINITIALISED=0,
    SYSTEMALARMS_ALARM_OK=1,
    SYSTEMALARMS_ALARM_WARNING=2,
    SYSTEMALARMS_ALARM_CRITICAL=3,
    SYSTEMALARMS_ALARM_ERROR=4
} SystemAlarmsAlarmOptions;

// Array element names for field Alarm
typedef enum {
    SYSTEMALARMS_ALARM_SYSTEMCONFIGURATION=0,
    SYSTEMALARMS_ALARM_BOOTFAULT=1,
    SYSTEMALARMS_ALARM_OUTOFMEMORY=2,
    SYSTEMALARMS_ALARM_STACKOVERFLOW=3,
    SYSTEMALARMS_ALARM_CPUOVERLOAD=4,
    SYSTEMALARMS_ALARM_EVENTSYSTEM=5,
    SYSTEMALARMS_ALARM_TELEMETRY=6,
    SYSTEMALARMS_ALARM_RECEIVER=7,
    SYSTEMALARMS_ALARM_MANUALCONTROL=8,
    SYSTEMALARMS_ALARM_ACTUATOR=9,
    SYSTEMALARMS_ALARM_ATTITUDE=10,
    SYSTEMALARMS_ALARM_NAV=11,
    SYSTEMALARMS_ALARM_SENSORS=12,
    SYSTEMALARMS_ALARM_MAGNETOMETER=13,
    SYSTEMALARMS_ALARM_AIRSPEED=14,
    SYSTEMALARMS_ALARM_STABILIZATION=15,
    SYSTEMALARMS_ALARM_GUIDANCE=16,
    SYSTEMALARMS_ALARM_PATHPLAN=17,
    SYSTEMALARMS_ALARM_BATTERY=18,
    SYSTEMALARMS_ALARM_FLIGHTTIME=19,
    SYSTEMALARMS_ALARM_I2C=20,
    SYSTEMALARMS_ALARM_GPS=21
} SystemAlarmsAlarmElem;

// Number of elements for field Alarm
#define SYSTEMALARMS_ALARM_NUMELEM 22

/* Field ExtendedAlarmStatus information */

// Enumeration options for field ExtendedAlarmStatus
typedef enum __attribute__ ((__packed__)) {
    SYSTEMALARMS_EXTENDEDALARMSTATUS_NONE=0,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_REBOOTREQUIRED=1,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_FLIGHTMODE=2,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_UNSUPPORTEDCONFIG_ONESHOT=3,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_BADTHROTTLEORCOLLECTIVEINPUTRANGE=4,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_AUTOTUNE=5
} SystemAlarmsExtendedAlarmStatusOptions;

// Array element names for field ExtendedAlarmStatus
typedef enum {
    SYSTEMALARMS_EXTENDEDALARMSTATUS_SYSTEMCONFIGURATION=0,
    SYSTEMALARMS_EXTENDEDALARMSTATUS_BOOTFAULT=1
} SystemAlarmsExtendedAlarmStatusElem;

// Number of elements for field ExtendedAlarmStatus
#define SYSTEMALARMS_EXTENDEDALARMSTATUS_NUMELEM 2

/* Field ExtendedAlarmSubStatus information */

// Array element names for field ExtendedAlarmSubStatus
typedef enum {
    SYSTEMALARMS_EXTENDEDALARMSUBSTATUS_SYSTEMCONFIGURATION=0,
    SYSTEMALARMS_EXTENDEDALARMSUBSTATUS_BOOTFAULT=1
} SystemAlarmsExtendedAlarmSubStatusElem;

// Number of elements for field ExtendedAlarmSubStatus
#define SYSTEMALARMS_EXTENDEDALARMSUBSTATUS_NUMELEM 2



typedef struct __attribute__ ((__packed__)) {
    SystemAlarmsAlarmOptions SystemConfiguration;
    SystemAlarmsAlarmOptions BootFault;
    SystemAlarmsAlarmOptions OutOfMemory;
    SystemAlarmsAlarmOptions StackOverflow;
    SystemAlarmsAlarmOptions CPUOverload;
    SystemAlarmsAlarmOptions EventSystem;
    SystemAlarmsAlarmOptions Telemetry;
    SystemAlarmsAlarmOptions Receiver;
    SystemAlarmsAlarmOptions ManualControl;
    SystemAlarmsAlarmOptions Actuator;
    SystemAlarmsAlarmOptions Attitude;
    SystemAlarmsAlarmOptions Nav;
    SystemAlarmsAlarmOptions Sensors;
    SystemAlarmsAlarmOptions Magnetometer;
    SystemAlarmsAlarmOptions Airspeed;
    SystemAlarmsAlarmOptions Stabilization;
    SystemAlarmsAlarmOptions Guidance;
    SystemAlarmsAlarmOptions PathPlan;
    SystemAlarmsAlarmOptions Battery;
    SystemAlarmsAlarmOptions FlightTime;
    SystemAlarmsAlarmOptions I2C;
    SystemAlarmsAlarmOptions GPS;
}  SystemAlarmsAlarmData ;
typedef struct __attribute__ ((__packed__)) {
    SystemAlarmsAlarmOptions array[22];
}  SystemAlarmsAlarmDataArray ;
#define SystemAlarmsAlarmToArray( var ) UAVObjectFieldToArray( SystemAlarmsAlarmData, var )

typedef struct __attribute__ ((__packed__)) {
    SystemAlarmsExtendedAlarmStatusOptions SystemConfiguration;
    SystemAlarmsExtendedAlarmStatusOptions BootFault;
}  SystemAlarmsExtendedAlarmStatusData ;
typedef struct __attribute__ ((__packed__)) {
    SystemAlarmsExtendedAlarmStatusOptions array[2];
}  SystemAlarmsExtendedAlarmStatusDataArray ;
#define SystemAlarmsExtendedAlarmStatusToArray( var ) UAVObjectFieldToArray( SystemAlarmsExtendedAlarmStatusData, var )

typedef struct __attribute__ ((__packed__)) {
    uint8_t SystemConfiguration;
    uint8_t BootFault;
}  SystemAlarmsExtendedAlarmSubStatusData ;
typedef struct __attribute__ ((__packed__)) {
    uint8_t array[2];
}  SystemAlarmsExtendedAlarmSubStatusDataArray ;
#define SystemAlarmsExtendedAlarmSubStatusToArray( var ) UAVObjectFieldToArray( SystemAlarmsExtendedAlarmSubStatusData, var )


/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    SystemAlarmsAlarmData Alarm;
    SystemAlarmsExtendedAlarmStatusData ExtendedAlarmStatus;
    SystemAlarmsExtendedAlarmSubStatusData ExtendedAlarmSubStatus;

} __attribute__((packed)) SystemAlarmsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef SystemAlarmsDataPacked __attribute__((aligned(4))) SystemAlarmsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    SystemAlarmsDataPacked data;
    byte arr[SYSTEMALARMS_NUMBYTES];
 } SystemAlarmsDataUnion;

#endif // SYSTEMALARMS_H

/**
 * @}
 * @}
 */
