/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup VtolPathFollowerSettings VtolPathFollowerSettings
 * @brief Settings for the @ref VtolPathFollowerModule
 *
 * Autogenerated files and functions for VtolPathFollowerSettings Object
 *
 * @{
 *
 * @file       vtolpathfollowersettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the VtolPathFollowerSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: vtolpathfollowersettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef VTOLPATHFOLLOWERSETTINGS_H
#define VTOLPATHFOLLOWERSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define VTOLPATHFOLLOWERSETTINGS_OBJID 0x49B0AEBA
#define VTOLPATHFOLLOWERSETTINGS_ISSINGLEINST 1
#define VTOLPATHFOLLOWERSETTINGS_ISSETTINGS 1
#define VTOLPATHFOLLOWERSETTINGS_ISPRIORITY 0
#define VTOLPATHFOLLOWERSETTINGS_NUMBYTES sizeof(VtolPathFollowerSettingsData)

/* Field HorizontalVelMax information */

/* Field VerticalVelMax information */

/* Field CourseFeedForward information */

/* Field HorizontalPosP information */

/* Field VerticalPosP information */

/* Field HorizontalVelPID information */

// Array element names for field HorizontalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_HORIZONTALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_HORIZONTALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_HORIZONTALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_HORIZONTALVELPID_BETA=3
} VtolPathFollowerSettingsHorizontalVelPIDElem;

// Number of elements for field HorizontalVelPID
#define VTOLPATHFOLLOWERSETTINGS_HORIZONTALVELPID_NUMELEM 4

/* Field VerticalVelPID information */

// Array element names for field VerticalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_VERTICALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_VERTICALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_VERTICALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_VERTICALVELPID_BETA=3
} VtolPathFollowerSettingsVerticalVelPIDElem;

// Number of elements for field VerticalVelPID
#define VTOLPATHFOLLOWERSETTINGS_VERTICALVELPID_NUMELEM 4

/* Field ThrustLimits information */

// Array element names for field ThrustLimits
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_THRUSTLIMITS_MIN=0,
    VTOLPATHFOLLOWERSETTINGS_THRUSTLIMITS_NEUTRAL=1,
    VTOLPATHFOLLOWERSETTINGS_THRUSTLIMITS_MAX=2
} VtolPathFollowerSettingsThrustLimitsElem;

// Number of elements for field ThrustLimits
#define VTOLPATHFOLLOWERSETTINGS_THRUSTLIMITS_NUMELEM 3

/* Field VelocityFeedforward information */

/* Field FlyawayEmergencyFallbackTriggerTime information */

/* Field EmergencyFallbackAttitude information */

// Array element names for field EmergencyFallbackAttitude
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKATTITUDE_ROLL=0,
    VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKATTITUDE_PITCH=1
} VtolPathFollowerSettingsEmergencyFallbackAttitudeElem;

// Number of elements for field EmergencyFallbackAttitude
#define VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKATTITUDE_NUMELEM 2

/* Field EmergencyFallbackYawRate information */

// Array element names for field EmergencyFallbackYawRate
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKYAWRATE_KP=0,
    VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKYAWRATE_MAX=1
} VtolPathFollowerSettingsEmergencyFallbackYawRateElem;

// Number of elements for field EmergencyFallbackYawRate
#define VTOLPATHFOLLOWERSETTINGS_EMERGENCYFALLBACKYAWRATE_NUMELEM 2

/* Field MaxRollPitch information */

/* Field BrakeRate information */

/* Field BrakeMaxPitch information */

/* Field BrakeHorizontalVelPID information */

// Array element names for field BrakeHorizontalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_BRAKEHORIZONTALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_BRAKEHORIZONTALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_BRAKEHORIZONTALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_BRAKEHORIZONTALVELPID_BETA=3
} VtolPathFollowerSettingsBrakeHorizontalVelPIDElem;

// Number of elements for field BrakeHorizontalVelPID
#define VTOLPATHFOLLOWERSETTINGS_BRAKEHORIZONTALVELPID_NUMELEM 4

/* Field BrakeVelocityFeedforward information */

/* Field LandVerticalVelPID information */

// Array element names for field LandVerticalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_LANDVERTICALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_LANDVERTICALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_LANDVERTICALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_LANDVERTICALVELPID_BETA=3
} VtolPathFollowerSettingsLandVerticalVelPIDElem;

// Number of elements for field LandVerticalVelPID
#define VTOLPATHFOLLOWERSETTINGS_LANDVERTICALVELPID_NUMELEM 4

/* Field AutoTakeoffVerticalVelPID information */

// Array element names for field AutoTakeoffVerticalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_AUTOTAKEOFFVERTICALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_AUTOTAKEOFFVERTICALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_AUTOTAKEOFFVERTICALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_AUTOTAKEOFFVERTICALVELPID_BETA=3
} VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDElem;

// Number of elements for field AutoTakeoffVerticalVelPID
#define VTOLPATHFOLLOWERSETTINGS_AUTOTAKEOFFVERTICALVELPID_NUMELEM 4

/* Field VelocityRoamMaxRollPitch information */

/* Field VelocityRoamHorizontalVelPID information */

// Array element names for field VelocityRoamHorizontalVelPID
typedef enum {
    VTOLPATHFOLLOWERSETTINGS_VELOCITYROAMHORIZONTALVELPID_KP=0,
    VTOLPATHFOLLOWERSETTINGS_VELOCITYROAMHORIZONTALVELPID_KI=1,
    VTOLPATHFOLLOWERSETTINGS_VELOCITYROAMHORIZONTALVELPID_KD=2,
    VTOLPATHFOLLOWERSETTINGS_VELOCITYROAMHORIZONTALVELPID_BETA=3
} VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDElem;

// Number of elements for field VelocityRoamHorizontalVelPID
#define VTOLPATHFOLLOWERSETTINGS_VELOCITYROAMHORIZONTALVELPID_NUMELEM 4

/* Field UpdatePeriod information */

/* Field TreatCustomCraftAs information */

// Enumeration options for field TreatCustomCraftAs
typedef enum __attribute__ ((__packed__)) {
    VTOLPATHFOLLOWERSETTINGS_TREATCUSTOMCRAFTAS_FIXEDWING=0,
    VTOLPATHFOLLOWERSETTINGS_TREATCUSTOMCRAFTAS_VTOL=1,
    VTOLPATHFOLLOWERSETTINGS_TREATCUSTOMCRAFTAS_GROUND=2
} VtolPathFollowerSettingsTreatCustomCraftAsOptions;

/* Field ThrustControl information */

// Enumeration options for field ThrustControl
typedef enum __attribute__ ((__packed__)) {
    VTOLPATHFOLLOWERSETTINGS_THRUSTCONTROL_MANUAL=0,
    VTOLPATHFOLLOWERSETTINGS_THRUSTCONTROL_AUTO=1
} VtolPathFollowerSettingsThrustControlOptions;

/* Field YawControl information */

// Enumeration options for field YawControl
typedef enum __attribute__ ((__packed__)) {
    VTOLPATHFOLLOWERSETTINGS_YAWCONTROL_MANUAL=0,
    VTOLPATHFOLLOWERSETTINGS_YAWCONTROL_TAILIN=1,
    VTOLPATHFOLLOWERSETTINGS_YAWCONTROL_MOVEMENTDIRECTION=2,
    VTOLPATHFOLLOWERSETTINGS_YAWCONTROL_PATHDIRECTION=3,
    VTOLPATHFOLLOWERSETTINGS_YAWCONTROL_POI=4
} VtolPathFollowerSettingsYawControlOptions;

/* Field FlyawayEmergencyFallback information */

// Enumeration options for field FlyawayEmergencyFallback
typedef enum __attribute__ ((__packed__)) {
    VTOLPATHFOLLOWERSETTINGS_FLYAWAYEMERGENCYFALLBACK_DISABLED=0,
    VTOLPATHFOLLOWERSETTINGS_FLYAWAYEMERGENCYFALLBACK_ENABLED=1,
    VTOLPATHFOLLOWERSETTINGS_FLYAWAYEMERGENCYFALLBACK_ALWAYS=2,
    VTOLPATHFOLLOWERSETTINGS_FLYAWAYEMERGENCYFALLBACK_DEBUGTEST=3
} VtolPathFollowerSettingsFlyawayEmergencyFallbackOptions;



typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsHorizontalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsHorizontalVelPIDDataArray ;
#define VtolPathFollowerSettingsHorizontalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsHorizontalVelPIDData, var )

typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsVerticalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsVerticalVelPIDDataArray ;
#define VtolPathFollowerSettingsVerticalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsVerticalVelPIDData, var )

typedef struct __attribute__ ((__packed__)) {
    float Min;
    float Neutral;
    float Max;
}  VtolPathFollowerSettingsThrustLimitsData ;
typedef struct __attribute__ ((__packed__)) {
    float array[3];
}  VtolPathFollowerSettingsThrustLimitsDataArray ;
#define VtolPathFollowerSettingsThrustLimitsToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsThrustLimitsData, var )

typedef struct __attribute__ ((__packed__)) {
    float Roll;
    float Pitch;
}  VtolPathFollowerSettingsEmergencyFallbackAttitudeData ;
typedef struct __attribute__ ((__packed__)) {
    float array[2];
}  VtolPathFollowerSettingsEmergencyFallbackAttitudeDataArray ;
#define VtolPathFollowerSettingsEmergencyFallbackAttitudeToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsEmergencyFallbackAttitudeData, var )

typedef struct __attribute__ ((__packed__)) {
    float kP;
    float Max;
}  VtolPathFollowerSettingsEmergencyFallbackYawRateData ;
typedef struct __attribute__ ((__packed__)) {
    float array[2];
}  VtolPathFollowerSettingsEmergencyFallbackYawRateDataArray ;
#define VtolPathFollowerSettingsEmergencyFallbackYawRateToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsEmergencyFallbackYawRateData, var )

typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsBrakeHorizontalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsBrakeHorizontalVelPIDDataArray ;
#define VtolPathFollowerSettingsBrakeHorizontalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsBrakeHorizontalVelPIDData, var )

typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsLandVerticalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsLandVerticalVelPIDDataArray ;
#define VtolPathFollowerSettingsLandVerticalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsLandVerticalVelPIDData, var )

typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDDataArray ;
#define VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDData, var )

typedef struct __attribute__ ((__packed__)) {
    float Kp;
    float Ki;
    float Kd;
    float Beta;
}  VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDData ;
typedef struct __attribute__ ((__packed__)) {
    float array[4];
}  VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDDataArray ;
#define VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDToArray( var ) UAVObjectFieldToArray( VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDData, var )


/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float HorizontalVelMax;
    float VerticalVelMax;
    float CourseFeedForward;
    float HorizontalPosP;
    float VerticalPosP;
    VtolPathFollowerSettingsHorizontalVelPIDData HorizontalVelPID;
    VtolPathFollowerSettingsVerticalVelPIDData VerticalVelPID;
    VtolPathFollowerSettingsThrustLimitsData ThrustLimits;
    float VelocityFeedforward;
    float FlyawayEmergencyFallbackTriggerTime;
    VtolPathFollowerSettingsEmergencyFallbackAttitudeData EmergencyFallbackAttitude;
    VtolPathFollowerSettingsEmergencyFallbackYawRateData EmergencyFallbackYawRate;
    float MaxRollPitch;
    float BrakeRate;
    float BrakeMaxPitch;
    VtolPathFollowerSettingsBrakeHorizontalVelPIDData BrakeHorizontalVelPID;
    float BrakeVelocityFeedforward;
    VtolPathFollowerSettingsLandVerticalVelPIDData LandVerticalVelPID;
    VtolPathFollowerSettingsAutoTakeoffVerticalVelPIDData AutoTakeoffVerticalVelPID;
    float VelocityRoamMaxRollPitch;
    VtolPathFollowerSettingsVelocityRoamHorizontalVelPIDData VelocityRoamHorizontalVelPID;
    uint16_t UpdatePeriod;
    VtolPathFollowerSettingsTreatCustomCraftAsOptions TreatCustomCraftAs;
    VtolPathFollowerSettingsThrustControlOptions ThrustControl;
    VtolPathFollowerSettingsYawControlOptions YawControl;
    VtolPathFollowerSettingsFlyawayEmergencyFallbackOptions FlyawayEmergencyFallback;

} __attribute__((packed)) VtolPathFollowerSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef VtolPathFollowerSettingsDataPacked __attribute__((aligned(4))) VtolPathFollowerSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    VtolPathFollowerSettingsDataPacked data;
    byte arr[VTOLPATHFOLLOWERSETTINGS_NUMBYTES];
 } VtolPathFollowerSettingsDataUnion;

#endif // VTOLPATHFOLLOWERSETTINGS_H

/**
 * @}
 * @}
 */
